eclipse/xtext-core

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/syntaxcoloring/IEditorHighlightingConfigurationProvider.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/syntaxcoloring/IEditorHighlightingConfigurationProvider.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
In Orion's highlighting configuration all patterns that precede the last block pattern are treated as block patterns. Up to now the position of the `doc_block` pattern in the generated grammar causes all section patterns to become block patterns which breaks the bracket matching.
See also Orion bug #497097
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
=> [web] Fix for broken bracket matching in Orion

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
When the `ignoreCase` option is active, the set of keywords returned by the KeywordHelper may be smaller than the whole set of keywords. This change fixes a case where a duplicate rule was generated due to the `ignoreCase` option.
Tested in `org.eclipse.xtext.lexer.IgnoreCaseLexerTestLanguage`.
=> [generator] Use KeywordHelper to obtain all keywords

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java
The default encoding of grammar files is set to the one from the generator configuration. This is required if the grammar file is referenced with a classpath URI or it's not in an Eclipse-configured project.
=> [generator] Added initialization of encoding for the Xtext grammar language

org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GenerateSerializerLanguages.mwe2
GenerateSerializerLanguages.mwe2 should behave like GenerateAllTestLanguages.mwe2
=> fixed #60.

org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
=> [MANIFEST.MF-cleanup] splitting lines should also work on UNIX newlines

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/AbstractPartialParserTest.java
It should also test if node.getGrammarElement() is correct
=> make AbstractPartialParsrTest more strict

org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/util/NodeModelUtilsTest.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java
This guard adds more safety, but the actual NPE reason is fixed by
https://github.com/eclipse/xtext-xtend/pull/26
=> [478377] Add null guard

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalProvider.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalProvider.java
[500192] IdeContentProposalProvider - Don't call Scope Provider with null model
=> [500192] IdeContentProposalProvider - Don't call Scope Provider with null model

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
[445175] Missing error message on invalid alternative assignments with cross references
=> [445175] Missing error message on invalid alternative assignments with cross references

org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/ManifestAccess.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/ManifestAccess.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.java
Line delimiter is determined by CodeConfig and reached into MergeableManifest.
=> [378980] Make line delimiter for Manifest configurable by CodeConfig

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java
=> [378980] Adjusted test: Manifest line break is system dependent

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/.launch/Generate MyDsl (mydsl) Language Infrastructure.launch, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
- Launch config for Runtime Eclipse is only generated when the runtime
project is a plugin project.
- Launch config for Xtext workflow is dependent on the build system. For
plain Maven projects the launch config uses the m2e launcher, for Gradle
builds buildship is launched.
=> [#112] Generate launch configs for Xtext workflow and Runtime Eclipse

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/ITextReplacerContext.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java
=> fixed #97 [Formatting2/auto-wrap] never wrap preceding lines

org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/EmitterNodeUtil.java
This disables a check with a legacy impl. 
The check should never be active at runtime.
Unfortunately, the legacy impl has a bug when a node's parent is null.
=> fixed eclipse/xtext-eclipse#100 serializer/performance fix regression

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
The location/condition of generating that comment was simply wrong,
should now be in line with the former template in ['ParameterizedLexerGrammar.xpt'](https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/ex/common/ParameterizedLexerGrammar.xpt) of the old 'org.eclipse.xtext.generator' project.
Signed-off-by: Christian Schneider christian.schneider@typefox.io
=> [xtext.xtext.generator] moved of a generated comment in 'AbstractAntlrGrammarGenerator'

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/antlr/FollowElementComputer.java
… by a DI `provider.get()` call  allowing to inject a customized calculator
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
=> [xtext.ide] replacement of 'new FollowElementCalculator()' constructor call in 'FollowElementComputer'

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractEObjectRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeModelBasedRegionAccessBuilder.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringEObjectRegion.java
[#170] [Formatter2] Typo in the AbstractEObjectRegion class
=> [#170] [Formatter2] Typo in the AbstractEObjectRegion class

org.eclipse.xtext/src/org/eclipse/xtext/linking/impl/DefaultLinkingService.java
To set a breakpoint that hits when a cross reference can not be resolved
it should not be necessary to use a conditional breakpoint. A regular
breakpoint should be enough.
Signed-off-by: Moritz Eysholdt moritz.eysholdt@typefox.io
=> make DefaultLinkingService#getLinkedObjects() easier to debug

org.eclipse.xtext.tests/src/org/eclipse/xtext/filesystem/URIBasedFileSystemAccessTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/filesystem/URIBasedFileSystemAccessTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/URIBasedFileSystemAccess.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/URIBasedFileSystemAccess.java
A FNFE was thrown instead of returning with false.
Signed-off-by: Akos Kitta <kittaakos@gmail.com>
=> Fixed issue in URI based file system access when checking missing files.

gradle/eclipse-project-layout.gradle, org.eclipse.xtext.ide.tests/.classpath, org.eclipse.xtext.ide/.classpath, org.eclipse.xtext.testing/.classpath, org.eclipse.xtext.testlanguages.ide/.classpath, org.eclipse.xtext.testlanguages/.classpath, org.eclipse.xtext.tests/.classpath, org.eclipse.xtext.util/.classpath, org.eclipse.xtext.xtext.generator/.classpath, org.eclipse.xtext.xtext.wizard/.classpath, org.eclipse.xtext/.classpath
Modify classpath on Gradle import to set the ignore_optional_problems
flag for source folders ending with *-gen, but not for xtend-gen
=> [#5] Ignore optional problems on *-gen folder

gradle/java-compiler-settings.gradle
This should be the change that ensures that the xtextBuilder is added before javabuilder. But with the current Gradle/Buildship version the order is changed back afterwards.
This PR can be applied only after clarification of the cause.
=> [eclipse/xtext/#1088] Add xtextBuilder command as first build command

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ecore2xtext/Ecore2XtextGrammarCreator.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ecore2xtext/Ecore2XtextGrammarCreator.java
For comparison with null the triple (not) equal operator should be used.
Resolved compiler warnings
=> [eclipse/xtext#1089] Replace (not)equal operators by triple (not)equals

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorNaming.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorNaming.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
`XtextGeneratorNaming` contained methods like `getGenericIdeBasePackage` that were already released in 2.10 (even in 2.9 I guess). Additional methods like `getIdeBasePackage` were added as part of https://github.com/eclipse/xtext-core/issues/11 .
This PR consolidates those getters by removing the superfluous ones and switches the additional ones to the released name scheme.
=> [generator] consolidation of IDE-related names in 'XtextGeneratorNaming'

org.eclipse.xtext/src/org/eclipse/xtext/parser/antlr/AbstractInternalAntlrParser.java
Initializing allRules can be slow, for some complicated languages it may be interesting to cache the value but currently that's not possible without using reflection. This change opens the api of AbstractInternalAntlrParser a little bit to allow this modification.
Signed-off-by: Lieven Lemiengre <lieven.lemiengre@sigasi.com>
=> Allow customisation of allRules creation in AbstractInternalAntlrParser

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
This PR adds `org.eclipse.xtext.common.types` to the dependencies of MWE executions in 'RuntimeProjectDescriptor's build file templates.
Currently `org.eclipse.xtext.xbase` is added to the compile dependencies of runtime projects by default, but if people decide not including xbase anymore the workflow execution doesn't work anymore.
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
=> [xtext.wizard] minor improvement of runtime project build file templates

gradle/p2-deployment.gradle, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.tests/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java, releng/releng-target/xtext-core.target.target
* consolidated version of 'org.junit' with our reference in 'gradle/versions.gradle' (currently 4.12)
* added dependency to 'junit:junit:4.12' with scope 'testCompile' to templates of 'pom.xml' + 'build.gradle', is required as `org.eclipse.xtext.testing`s optional dependency to `junit:junit` is not exposed to its `pom.xml` created by gradle
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
=> [xtext.testing + xtext.wizard] fix/improvement of build config of test projects in 'TestProjectDescriptor'

build.gradle, gradle/bootstrap-setup.gradle, gradle/eclipse-project-layout.gradle, gradle/java-compiler-settings.gradle, gradle/maven-deployment.gradle, gradle/versions.gradle, gradle/xtend-compiler-settings.gradle, org.eclipse.xtext.xtext.bootstrap/build.gradle
This ensures that the source mapping is set up correctly in the build artifacts.
=> Apply Xtend Gradle plugin during the build

org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/SequencerTestLanguageStandaloneSetup.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/SyntacticSequencerTestLanguageInjectorProvider.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/TokenSerializerTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/TokenSerializerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/tokens/CrossReferenceSerializer.java
The new TokenSerializerTest reveals the regression: output without the fix is
```
java.lang.RuntimeException: No EObjectDescription could be found in Scope SingleCrossReference.ref3 for SingleCrossReference
Semantic Object: Model.x5->SingleCrossReference'myref'
URI: dummy.syntacticsequencertestlanguage
EStructuralFeature: syntacticsequencertest::SingleCrossReference.ref3
at org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic$ExceptionThrowingAcceptor.accept(ISerializationDiagnostic.java:131)
at org.eclipse.xtext.serializer.tokens.CrossReferenceSerializer.getCrossReferenceNameFromScope(CrossReferenceSerializer.java:140)
at org.eclipse.xtext.serializer.tokens.CrossReferenceSerializer.serializeCrossRef(CrossReferenceSerializer.java:113)
at …
```
=> Fixed CrossReferenceSerializer regression for special proxy URI formats

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/LanguageModule.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/LanguageModule.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
- XtextGeneratorLanguage was injecting its members incorrectly.
- LanguageModule must bind the language to a provider to prevent Guice from injecting its members implicitly (masking the previous bug).
- `EMFGeneratorFragment2.updateBuildProperties()` should do nothing when build.properties does not exist.
=> [generator] Some fixes

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/formatter/FormatterTestHelper.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormattingConflictTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/RegionSetTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormattingConflictTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/RegionSetTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/FormatterRequest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/ArrayListTextSegmentSet.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/RegionTraceMissingException.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextSegmentSet.java
This change:
- introduces a flag that by default disables creation of stack traces
- lets the formatter do a second pass on conflict with that flag enabled
This combines the benefits of both worlds:
- performance without the need for tweaking
- debug information without the need to enable some magic config
see 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=508894
https://bugs.eclipse.org/bugs/show_bug.cgi?id=507174
https://github.com/eclipse/xtext-core/pull/195
=> [formatter/performance] Don't create stack traces

org.eclipse.xtext/src/org/eclipse/xtext/grammaranalysis/impl/GrammarElementTitleSwitch.java
If the loaded grammar had broken cross-references, the code could lead to an NPE.
=> Added null / proxy check to GrammarElementTitleSwitch

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/debug/TextRegionAccessToString.java
see https://github.com/eclipse/xtext-core/issues/12
=> fixed #12: [formatter] IllegalArgumentException in NodeRegion.toString()

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
Since now Xtend issues a warning if you use != with null.
=> generated Xtend servlet class should use !== instead of !=

build.gradle, gradle/eclipse-project-layout.gradle, gradle/java-compiler-settings.gradle, gradle/mwe2-workflows.gradle, org.eclipse.xtext.ide.tests/build.gradle, org.eclipse.xtext.ide.tests/model/generated/PartialContentAssistTestLanguage.genmodel, org.eclipse.xtext.ide.tests/model/generated/TestLanguage.genmodel, org.eclipse.xtext.testlanguages/build.gradle, org.eclipse.xtext.tests/build.gradle, org.eclipse.xtext.tests/emf-gen/org/eclipse/xtext/metamodelreferencing/tests/ecorePerNsURI/impl/EcorePerNsURIPackageImpl.java, org.eclipse.xtext.tests/emf-gen/org/eclipse/xtext/metamodelreferencing/tests/ecorePerPlatformPlugin/impl/EcorePerPlatformPluginPackageImpl.java, org.eclipse.xtext.tests/emf-gen/org/eclipse/xtext/metamodelreferencing/tests/ecorePerPlatformResource/impl/EcorePerPlatformResourcePackageImpl.java, org.eclipse.xtext.tests/plugin.xml, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/unorderedGroups/serializer/ExUnorderedGroupsTestLanguageSyntacticSequencer.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parser/unorderedGroups/serializer/SimpleUnorderedGroupsTestLanguageSyntacticSequencer.java, org.eclipse.xtext.xtext.bootstrap/.gitignore, org.eclipse.xtext.xtext.bootstrap/build.gradle
Now you can generate *all* test languages (`org.eclipse.xtext.testlanguages`, `org.eclipse.xtext.tests`, `org.eclipse.xtext.ide.tests`) by calling
```
./gradlew generateTestLanguages
```
=> Generate Xtext languages from Gradle

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
Return Object insteadof null in LanguageServer.shutdown.
Solves #240
=> Return Object insteadof null in LanguageServer.shutdown.

gradle/upstream-repositories.gradle, gradle/versions.gradle
The Xtext 2.11.0 release needs a fixed LSP4J version to depend on.
=> Switched to LSP4J 0.1.0 release

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.java
The project wizard now adds .xtext.junit4 and .xbase.junit as deps in the .ui.tests project since these bundles still contain the UI testing classes. Accordingly, the mwe2 does the same (but still respecting skipXbaseTestingPackage).
Note that the additional extracted methods in the Junit4Fragment2.xtend: if useDeprecatedClasses is used in the mwe2, then .xtext.junit4 and .xbase.junit will be added twice in the collection of the required bundles for the .ui.tests project. However, when the MANIFEST is updated, possible duplicates are automatically dealt with, thus it is safe to do so.
Closes #244
=> Lb task 244 junit4 fragment2

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormatterReplacementsTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormatterReplacementsTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java
=> fixed #251: Formatter erroneously applies default formatting

org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
First step for #223. We should consider removing this property, which is possible since XtextGeneratorLanguage is marked with `@noextend`.
=> Deprecated XtextGeneratorLanguage.generateXtendStubs

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/AbstractParallelScenarioRunner.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/AbstractScenarioRunner.java
With JUnit 4.12 the class was made public API, the old class is
deprecated.
=> Change import of AssumptionViolatedException

org.eclipse.xtext.util/src/org/eclipse/xtext/util/internal/Nullable.java
Introduce Nullable Annotation to allow Null-Injections with google guice. see https://github.com/eclipse/xtext-eclipse/issues/153 for details
=> Introduce Nullable Annotation

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/terminalrules/UnicodeTest.java
run test with UTF-8 always #280
=> run test with UTF-8 always #280

org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/ContainerState.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/DelegatingIAllContainerAdapter.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/FlatResourceSetBasedAllContainersState.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/IAllContainersState.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/LiveShadowedAllContainerState.java
This change adds a default method 
boolean containsURI(String containerHandle, URI candidateURI)
to IAllContainersState, so that implementations can introduce 
a faster algorithm that leverages the internals data structures.
=> fixed #294 improve performance of IContainerState#contains(URI)

org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/StateBasedContainer.java
When using huge models, the getContents() call can consume runtime in the order of minutes and more. Shorten runtime by only asking it for much faster isEmpty().
I've not tested the code in our custom xtext installation, since I still fail to compile the complete xtext-core.
Signed-off-by: Michael Keppler <michael.keppler@gmx.de>
=> refactor: improve performance of StateBasedContainer

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/Flaky.java
This annotation was still present in .xtext.junit4, so why not copying
that into the new .xtext.testing and then later deprecate the one in
.xtext.junit4?
=> Copied Flaky into .xtext.testing

org.eclipse.xtext/src/org/eclipse/xtext/validation/IssueSeveritiesProvider.java
The function `getValueProvider` is defined in `IssueSeveritiesProvider` for replying the value provider instance. 
This function seems to be defined as protected in order to be overriden. But is it not called from the rest of the code of `IssueSeveritiesProvider`. This PR fixes this issue.
=> Use getValuesProvider function in IssueSeveritiesProvider.

org.eclipse.xtext.tests/src/org/eclipse/xtext/tasks/DefaultTaskFinderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskFinderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskFinder.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskFinder.java
[380449] Enhancements to Task Finder
- Introduced a hook to allow stripping of the node text before calling the task parser
- Stripped trailing comment in tasks
=> [380449] Enhancements to Task Finder

org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/FilterUriContainer.java
it's called often from e.g. SelectableBasedScope.createScope(...)
=> fixed #292 Improve performance of FilterUriContainer#isEmpty()

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/TypeReferenceTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/TypeReferenceTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TypeReference.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TypeReference.java
[508810] Referencing EStringToStringMapEntry results in compile Error in generated Abstract*SemanticSequencer
=> [508810] Referencing EStringToStringMapEntry results in compile Error in generated Abstract*SemanticSequencer

org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/CompositeGeneratorNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/IndentNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/NewLineNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TextNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TraceNode.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/CompositeGeneratorNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/IndentNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/NewLineNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TextNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TraceNode.java
It can be very useful to post-process the resulting tree of the generator. This change makes all generator node types mutable.
Also changed `equals()`, `hashCode()`, and `toString()` to be consistent for all node types.
=> Allow postprocessing on generator result tree

org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/internal/AbstractTraceForURIProvider.java
refactored method to return null when precondition is not satisfied to remove one indentation layer
removed null guard for projectConfig later in the method
=> handle null argument for projectConfig

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ServerLauncher.xtend
The whitespaces make it not work on Windows. 
I'm not sure if the suggested solution is the best, so take it just as a suggestion.
=> server: file log name has whitespace

org.eclipse.xtext.util/META-INF/MANIFEST.MF
Increased guava version to include version 21.
https://github.com/eclipse/xtext-lib/issues/30
=> Increased guava version to include version 21. 

org.eclipse.xtext/src/org/eclipse/xtext/formatting/impl/AbstractDeclarativeFormatter.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/TextRegionAccessBuildingSequencer.java
added logging to inform the user that calling the formatter with an non resource eobject is a bad idea
=> added logging to inform the user that calling the formatter with an non resource eobject is a bad idea

org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TracedAccessors.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TracedAccessorsProcessor.java
dont generate traced accessor for java.lang.Object#getClass
=> dont generate traced accessor for java.lang.Object#getClass

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/WorkspaceManagerTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/WorkspaceManagerTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java
I've split `didOpen`, `didChange`, `didClose` and `didChangeWatchedFiles` to 2 write requests:
- applying document changes - performed synchronously, cannot be canceled
- building - performed asynchronously, can be canceled
In that way, we preserve the order of document changes and don't lose them, and at the same time are able to cancel builds.
Read requests are handled as before, so they can be canceled only by the client but not by another request. I've tried to cancel them with write requests but it leads to unexpectedly canceled requests on the client side.
=> [ls] cancellable builds

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
The EEF used to produce the following code:
```
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {
@Override
protected Bundle getBundle() {
return MydslActivator.getInstance().getBundle();
}
@Override
protected Injector getInjector() {
return MydslActivator.getInstance().getInjector(MydslActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL);
}
}
```
This raises a NPE when the activator was not started and hence getInstance() returns null. This can happen due to configuration issues and happens quite frequently.
This change will produce the following code:
```
@Override
protected Bundle getBundle() {
return Platform.getBundle(MydslActivator.PLUGIN_ID);
}
@Override
protected Injector getInjector() {
MydslActivator activator = MydslActivator.getInstance(); …
```
=> safe retrieval of bundle in EEF

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/containers/LiveShadowedAllContainerStateTest.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/LiveShadowedAllContainerState.java
[519299] LiveShadowedAllContainerState.containsURI() breaks scoping while refactoring (regression)
=> [519299] LiveShadowedAllContainerState.containsURI() breaks scoping while refactoring (regression)

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/ArrayListTextSegmentSet.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextSegmentSet.java
The previous fix 
https://github.com/eclipse/xtext-core/commit/906be319a46dc8d8d7e2e03a9a90e3b7e5afb494
dind't handle insertion of new ITextReplacers
=> fix #301: Improved support for IAutoWrapFormatter

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
It is wrong to initialize the remainingProjectNames with the newHashSet
function since it has the side effect that it will put the keySet as
whole as single entry to the new map instead of putting its values in
the map.
=> refreshWorkspaceConfig - Fixed initialization of remainingProjectNames

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ServerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ServerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
Fixes #378.
Also added missing `void` return types to some WorkspaceManager methods. This changes their signature, since previously `didOpen` and `didClose` returned the build result. However, `didChange` was already `void` before, so I assume the previous implicit return types were not on purpose.
=> Throw a response error when workspace is not initialized

org.eclipse.xtext.util/src/org/eclipse/xtext/util/IFileSystemScanner.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/IFileSystemScanner.java
According to contract of File.listFiles() the result can be null if an
I/O error occurred.
=> Added null guard for result of listFiles

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
=> fixed #398: formatting must not be applied outside requested regions

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/SemanticRegionFinderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/SemanticRegionFinderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeModelBasedRegionAccess.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringBasedRegionAccess.java
[468777] [formatter] ITextRegionAccess.regionForEObject(EObject) should throw exception for resource-external eobjects
=> [468777] [formatter] ITextRegionAccess.regionForEObject(EObject) should throw exception for resource-external eobjects

org.eclipse.xtext.ide/META-INF/MANIFEST.MF
made o.e.xtext.ide dep. to org.eclipse.core.runtime optional #446
=> made o.e.xtext.ide dep. to org.eclipse.core.runtime optional #446

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.java
[473623] Generator Support for enablement of XImportSection
=> [473623] Generator Support for enablement of XImportSection

org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/TestErrorAcceptor.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
[479137]improved Misleading error message 'Cannot create datatype' for terminal rule #91
=> [479137]improved Misleading error message 'Cannot create datatype' for terminal rule #91

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java
Decodes URL-encoded file paths.
Original implementation fails on Linux when LSP request contains Cyrillic characters in file name.
Signed-off-by: Alexander Kozinko <xcariba@gmail.com>
=> Decode file URL

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java
As the Javadoc says; the EMF file URI is created from the path of the
`java.io.File`. Paths with leading slashes are not valid paths on
Windows.
Task: #459 
Closes #459 
Signed-off-by: Akos Kitta <kittaakos@gmail.com>
=> GH-459: Aligned the test assertion in the failing case.

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/ITextReplacerContext.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/ArrayListTextSegmentSet.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextSegmentSet.java
To navigate the TextReplacers in reverse order, this change introduces a
reversed iterable. Thus, it is no longer necessary to copy all the 
TextReplacers into a list for reverse navigation.
=> [formatter/perf] Avoid calling List.newArrayList() during autowrap

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
Wrap ZipInputStream in a BufferedInputStream before reading from it with
with a DataInputStream or ObjectInputStream. This improves performance
quite significantly (overall roughly by a factor 4), as the
decompression works much more efficiently with larger chunks of data.
Signed-off-by: Knut Wannheden <knut.wannheden@paranor.ch>
=> #481: Improve performance of ResourceStorageLoadable

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TemplateNodeTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TemplateNodeTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TemplateNode.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TemplateNode.java
=> #483: Remove last whitespaces only when appending separator in for-loops

org.eclipse.xtext.tests/src/org/eclipse/xtext/EcoreUtil2Test.java, org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java, org.eclipse.xtext/src/org/eclipse/xtext/findReferences/ReferenceAcceptor.xtend, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultReferenceDescription.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultResourceDescriptionStrategy.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/findReferences/ReferenceAcceptor.java
Reference descriptions should always use path URIs for the source. 
=> [refactoring] Core part https://github.com/eclipse/xtext-eclipse/issues/284

org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/IRuntimeProjectConfig.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/RuntimeProjectConfig.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ImplicitFragment.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/IRuntimeProjectConfig.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/RuntimeProjectConfig.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF
- set lower bound for org.eclipse.xtext.xbase.lib to 2.11 (no API added afterwards)
- extended runtime project config by lower versions for Xbase/Xtend lib
- changed fragments to evaluate the lower version constraint of runtime project config to add a lower version constraint
=> [525746] Lower bound constraint for Xbase / Xtend libraries

org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValueConverters.java
```
java.lang.NullPointerException: null
at
org.eclipse.xtext.xtext.XtextValueConverters$1.internalToValue(XtextValueConverters.java:44)
at
org.eclipse.xtext.xtext.XtextValueConverters$1.internalToValue(XtextValueConverters.java:40)
at
org.eclipse.xtext.conversion.impl.AbstractNullSafeConverter.toValue(AbstractNullSafeConverter.java:31)
at
org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.toValue(AbstractDeclarativeValueConverterService.java:79)
at
org.eclipse.xtext.ide.serializer.impl.ReferenceUpdater.getQualifiedName(ReferenceUpdater.java:124)
at
org.eclipse.xtext.ide.serializer.impl.ReferenceUpdater.needsUpdating(ReferenceUpdater.java:146)
at
org.eclipse.xtext.ide.serializer.impl.ReferenceUpdater.update(ReferenceUpdater.java:172)
at …
```
=> Fix an NPE during ValueConversion of xtext.xtext.GrammarID

org.eclipse.xtext/META-INF/MANIFEST.MF
widened version range for asm to include version 6
https://github.com/eclipse/xtext-core/issues/501
=> widened version range for asm to include version 6

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
On windows the generated classpath in start scripts might become too
long. This can be avoided by additional configuration of the
appassembler-maven-plugin plugin:
- added option repositoryLayout=flat
- added option useWildcardClassPath=true
=> [#512] Maven AppAssembler - Reduce length of classpath

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TypeReference.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TypeReference.java
Fixed Issue with TypeReference and Custom Pre/Suffixes in EMF 
Fixes #530 
=> Fixed Issue with TypeReference and Custom Pre/Suffixes in EMF

org.eclipse.xtext.tests/src/org/eclipse/xtext/parsetree/formatter/XtextFormatterExpected.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parsetree/formatter/XtextFormatterMessy.xtext, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextFormatter.java
fixed formatting of annotations (e.g. @Override) in Xtext Grammars #534
=> fixed formatting of annotations (e.g. @Override) in Xtext Grammars #534

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameIssue520Test.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/IChangeSerializer.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeSemanticRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringBasedTextRegionAccessDiffAppender.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringSemanticRegion.java
Removed four unused imports and one unused local variable declaration.
=> Refactoring: Cleaning up warnings

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/debug/TextRegionsToStringTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/debug/TextRegionsToStringTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/debug/TextRegionsToString.java
Since windows line endings are replaced by unix line endings - i.e. the `\r` character is removed -, the result string can be shorter than the input string.
Since the loop iterating over the characters of the input string is limited to `maxLength + 1` iterations, the check `result.size() > maxLength` did not give the desired result in the presence of windows line endings.
Now, the number of iterations is incremented when a character is deleted from the string.
=> Fix for issue [#555]

org.eclipse.xtext/src/org/eclipse/xtext/generator/JavaIoFileSystemAccess.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/URIBasedFileSystemAccess.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/internal/AbstractTraceForURIProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/URIBasedFileSystemAccess.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java
[tracing] NPE thrown when a file is generated without traces 
https://github.com/eclipse/xtext-core/issues/359
=> [tracing] NPE thrown when a file is generated without traces

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainerTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainer.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainer.java
Here are more tests and a fix for new containers, as wished by @szarnekow .
Note that I am not aware of any EMF contract that defines what happens to the persistent state when you rename / delete a resource form a resource set. So these tests can only be done on the local state, i.e. I cannot rename / delete a resource form the shadowed global state by modifying the local resource set. Correct me if I am wrong, but AFAIK this doesn't work in the existing live scopes either.
=> GH-520 more tests for live scoping

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Fix for [#570]: Rules with an @Override annotation in a grammar without super grammar
now correctly display an error.
=> [#570] Added error message for invalid override

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp/jar-with-ecore-model.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar/jar-with-ecore-model.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/jar-with-ecore-model.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
Solves issue [#580]
- updated the wizard to use maven-assembly-plugin version 3.1.0
- updated the assembly descriptors to version 2.0.0
- updated the wizard to use maven-war-plugin version 3.2.0
- updated the tests to these versions, as well
=> [#580] Updated maven assembly/war plugins to latest versions

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
Related to issue [eclipse/xtext-core#582]
- updated from 1.0.19 to 1.0.20
- updated the version in the gradle file
- updated the version used by the wizard
- updated the version in one example
=> [#582] Updated version of xtext-gradle-plugin

org.eclipse.xtext/src/org/eclipse/xtext/documentation/impl/AbstractMultiLineCommentProvider.java
Duplicate `@Named` ids in AbstractMultiLineCommentProvider
https://github.com/eclipse/xtext/issues/1153
=> Duplicate @Named ids in AbstractMultiLineCommentProvider

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/ResourceRelocationContext.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/IChangeSerializer.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/ResourceRelocationContext.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext/src/org/eclipse/xtext/conversion/IValueConverter.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/IResourceDescription.java
Contribution to issue [eclipse/xtext#1155].
The remaining warnings related to javadoc do not seem to be caused by actual problems. For most of them I cannot even understand why there are warnings (e.g. there is a warning "... @propertyDescription can only be used in JavaFX properties ..." for `org.eclipse.xtext.generator.OutputConfiguration` although that class does not contain such an annotation).
=> [eclipse/xtext#1155] Cleaned up javadoc to remove some warnings.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.java
For xbase languages, the language specific editor is now correctly bound to XtextEditor instead of XbaseEditor (issue introduced in [eclipse/xtext-eclipse#463]).
Fixes [eclipse/xtext-xtend#334]
=> [eclipse/xtext-eclipse#463] Fixed faulty editor binding

org.eclipse.xtext/src/org/eclipse/xtext/naming/DefaultCopyQualifiedNameService.xtend, org.eclipse.xtext/src/org/eclipse/xtext/naming/ICopyQualifiedNameService.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/naming/DefaultCopyQualifiedNameService.java
Move implementation from CopyQualifiedNameService and
DefaultCopyQualifiedNameService to xtext core plugin.
Change-Id: I3ffdbbcda641cc4f70396f4274e42934e4248278
Signed-off-by: Arne Deutsch <arne@idedeluxe.com>
=> [xtext-eclipse#145] Create new implementations in core.

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/WrappingInjectorProvider.java
[#608] make sure that WrappingInjectorProvider records changes to the global registry even if the delegate itself is a IRegistryConfigurator and its injector is already created so that createInjector does not do anything that could be recorded
=> [#608] Fixed reuse issue with WrappingInjectorProvider

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.ui.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.ui.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.ui.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.ui.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
Configures profiles in the parent pom that contribute parts of the tycho-surefire-plugin args via profiles. Seperate profiles are defined for 'macos' and 'jdk9-or-newer'.
Mac profile was removed from the ui.tests project pom.
This change will enable projects configured for Java8 to be buildable on Java 8 and 9.
=> Support J9 for tycho based projects

org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/WorkspaceSymbolTest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/WorkspaceSymbolConfiguration.java
[#617] fixed typo in AbstractLanguageServerTest
=> [#617] fixed typo in AbstractLanguageServerTest

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
In development mode Xtext read the version from the 'Maven-Version'
attribute from org.eclipse.xtext.util manifest, which has a static value
of 'unspecified'. This gets replaced in a Gradle build, but does not
work when using the bundle in an Eclipse development environment.
=> [#627] Compute Xtext version from Bundle-Version

gradle/p2-deployment.gradle, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/xtext-core.target.target
- Upgrade to Xtext 2.13
- Upgrade to Tycho 1.1.0
- Use official Orbit
Regenerated pom.xml & target file with generateP2Build task
=> [eclipse/xtext#1170] Update p2-deployment.gradle & derived files

org.eclipse.xtext.tests/src/org/eclipse/xtext/naming/QualifiedNameTest.java, org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java
Avoid NPE when accidently invoked with null
Or shall we throw IllegalArgumentException?
=> startsWith: return false for null argument

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.java
The code mining provider base class has been renamed and only offers one
abstract method to implement by clients.
Also some minor cleanups.
=> [eclipse/xtext-eclipse#520] Adjust to latest API

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/formatting/FormattingService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java
- use IIndentationInformation for default
- don't use an immutable map to be able to override preferences in IFormatter2 impl
=> [formating] use indentation information

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/AbstractGeneratorFragmentTests.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/AbstractGeneratorFragmentTests.java
- Avoid double assignment of the globalStateMemento field.
=> [NONE] Fix Typo in AbstractGeneratorFragmentTests.xtend file.

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend
use grammar info instead of `MyDsl`.
cf. https://github.com/eclipse/xtext-core/pull/680
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
=> [validation] fix generation of issue code provider

org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/BacktrackingSemanticSequencer.java
Because quick fixes change the model and can cause any kind of mismatch
=> Fix eclipse/xtext-xtend#408: Allow mismatching node model

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/JavaVersionTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaVersion.java
This allows e.g. the selection of Java 10 in the new xtext project
wizard.
=> [eclipse/xtext#1177] Adapt JavaVersion to support Java 10.

gradle/versions.gradle, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UnknownProjectConfigTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/commands/CommandRegistryTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UnknownProjectConfigTest.java, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Fixes #694.
In LSP 3.6 the parameter type of `textDocument/completion` has changed from `TextDocumentPositionParams` to `CompletionParams`. While this is compatible in TypeScript (the new type adds only optional properties), it is a breaking change in Java :-/
LSP4J 0.4.0 is released next week. I set the dependency to the snapshot version here so we can include the update in the first RC. I'll change it to the released version as soon as it's available.
=> Updated to LSP4J 0.4.0

org.eclipse.xtext/src/org/eclipse/xtext/generator/FileSystemAccessQueue.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/FileSystemAccessQueue.java
ActiveAnnotationProcessors might run in parallel. Read operations should
wait until all write operations are ready to avoid race conditions.
=> [eclipse/xtext-eclipse#599] Support waiting operation.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1177] Switched Target Platform to Photon for Tycho Builds with Java 10
=> [eclipse/xtext#1177] Switched Target Platform to Photon for Tycho Builds with Java 10

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
[eclipse/xtext-web#53] updated to a newer jetty version that works better with asm 6.1
=> [eclipse/xtext-web#53] updated to a newer jetty version that works better with asm 6.1

org.eclipse.xtext.tests/src/org/eclipse/xtext/tasks/DefaultTaskParserTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParserTest.java, org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.xtend, org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskTagProvider.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParser.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskTagProvider.java
Using the DefaultTaskParser an exception is thrown when you add two tasks, one with a different casing as the other e.g. `todo` and `TODO`.
```
at com.google.common.collect.Maps.uniqueIndex(Maps.java:1385)
at com.google.common.collect.Maps.uniqueIndex(Maps.java:1341)
at org.eclipse.xtext.tasks.DefaultTaskParser.parseTasks(DefaultTaskParser.java:45)
at org.eclipse.xtext.tasks.DefaultTaskFinder.findTasks(DefaultTaskFinder.java:106)
at org.eclipse.xtext.tasks.DefaultTaskFinder.lambda$findTasks$0(DefaultTaskFinder.java:98)
at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
at …
```
=> Fixed duplicate key insertion with task tags

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
Do not inherit and modify (by reflection) the original
java.util.jar.Manifest but instead C&P and modify the code. Adapt
ManifestMergerTest by importing the new classes.
=> [#506] Removed reflection call.

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
This test case was removed since it failed for non-snapshot versions
within a Gradle build. This is typically the case when doing a release.
It was decided to remove this test case.
=> [#715] Remove test_getCurrent

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/MaxLineWidthDocument.java
[474468][eclipse/xtext-core#778] Fix bogus validation in MaxLineWidthDocument
=> [474468][eclipse/xtext-core#778] Fix bogus validation in MaxLineWidthDocument

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
An additional boolean flag was added to the generator fragment which allows to skip the generation of the validation block. This minimised the changes after regenerating Xtend.
=> [xtend#474] Allow to skip generation of validator ui contributions

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/builder/AbstractIncrementalBuilderTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/builder/AbstractIncrementalBuilderTest.java
[eclipse/xtext#1236]
added support for junit 4 and junit 5 in testing api
=> added support for junit 4 and junit 5 in testing api

org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
=> [#1238] Restrict org.antlr.runtime version to 3.2.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/occurrences/DefaultDocumentHighlightService.java
In the default case the ITextRegionTransformer is just a stateless utility class.
However in more complex cases it could need more information needing it to be protected.
=> Made textRegionTransformer protected in DefaultDocumentHighlightService

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/InjectionExtensionTest.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/XtextRunnerTest.java
Was Before/AfterTestExecutionCallback, which is executed after user
@BeforeEach callbacks. Injected members were not initialized in these
callbacks then.
=> [#795] Implement Before/AfterEachCallback

org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IncrementalBuilder.java
Added `protected` setters for the build context and the request.
Replaced the context and request assignments with setter calls.
Closes #798.
=> GH-798: Increased the visibility of the stateful incremental builder.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectSnapshotProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RecordingEmfResourceUpdater.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RecordingXtextResourceUpdater.java
When CrossReferences are not updated, recording the descriptions should
not be needed.
=> [ChangeSerializer] Don't record EObjectDescs if not needed.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext-core#824] Don't generate xpand dependency if not needed
=> [eclipse/xtext-core#824] Don't generate xpand dependency if not needed

org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/AbstractIndentationAwareUiTestLanguageValidator.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/AbstractPartialContentAssistTestLanguageValidator.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/AbstractPartialSerializationTestLanguageValidator.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/AbstractTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/backtracking/validation/AbstractBeeLangTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/backtracking/validation/AbstractExBeeLangTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/backtracking/validation/AbstractSimpleBeeLangTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/fileAware/validation/AbstractFileAwareTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/validation/AbstractNoJdtTestLanguageValidator.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/validation/XtextGrammarTestLanguageValidator.java, org.eclipse.xtext.tests/META-INF/MANIFEST.MF_gen, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parsetree/reconstr/serializer/SerializationErrorTestLanguageSemanticSequencer.java
[eclipse/xtext#1227] regenerated testlanguages
=> [eclipse/xtext#1227] regenerated testlanguages

org.eclipse.xtext/src/org/eclipse/xtext/serializer/tokens/CrossReferenceSerializer.java
=> Fix typo 'recordedErrros'->'recordedErrors' in CrossReferenceSerializer.

Jenkinsfile, gradle/bootstrap-setup.gradle, gradle/upstream-repositories.gradle, releng/pom.xml
Build steps defined in Jenkinsfile pass the built-in environment
variable 'JENKINS_URL' to the Gradle/Maven executions. This is evaluated
in the build scripts for upstream repository URLs. On Xtext JIPP this
will use upstream repos from JIPP. In local builds outside of Jenkins
the property defaults to Typefox CI like before.
https://ci.eclipse.org/xtext/job/xtext-core/job/kth_issue1224/1/console:
```
+ ./gradlew clean cleanGenerateXtext build createLocalMavenRepo -PuseJenkinsSnapshots=true -PJENKINS_URL=https://ci.eclipse.org/xtext/ -PcompileXtend=true -PignoreTestFailures=true --refresh-dependencies --continue
...
:org.eclipse.xtext.util:generateXtext
Download https://ci.eclipse.org/xtext//job/xtext-lib/job/master/lastStableBuild/artifact/build/maven-repository/org/eclipse/xtend/org.eclip …
```
=> [eclipse/xtext#1224] Detect local Jenkins environment

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/HierarchicalDocumentSymbolTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/HierarchicalDocumentSymbolTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolMapper.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/symbol/DocumentSymbolMapper.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/symbol/DocumentSymbolService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Added a test assertion to ensure `selectionRange` is always contained by the `range`.
Closes: #882.
=> GH-882: Fixed the inconsistency between the `range` and `selectionRange`.

gradle/bootstrap-setup.gradle, gradle/p2-deployment.gradle, gradle/versions.gradle, releng/releng-target/xtext-core.target.target
Refactored to use xtext_bootstrap property from versions.gradle
Changed target definition.
=> [eclipse/xtext#1272] Set Xtext bootstrap 2.15

org.eclipse.xtext/src/org/eclipse/xtext/parsetree/reconstr/impl/DefaultCommentAssociater.java
=> Fix a typo in the javadoc of the DefaultCommentAssociater class.

org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/AbstractXtextTests.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/KeywordHelperTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/KeywordHelperTest.java
=> [eclipse/xtext-1311] Perform KeywordHelperTest with ISO encoding

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMerger2Test.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/ManifestAccess.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/ManifestAccess.java
Adding extensive unit tests to ensure behaviour does not change.
Use only MergableMenufest2 internally.
=> #864: Rewrite MergeableManifest to MergeableManifest2 to avoid reflection

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java
Add a test that scans the classpath and reads/writes all found
MANIFEST.MF files.
=> #918: Integration MANIFEST.MF from classpath test

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/ISemanticHighlightingStyleToTokenMapper.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/semanticHighlight/ISemanticHighlightingStyleToTokenMapper.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.java
=> GH-924: Disabled the semantic highlighting with the default bindings.

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/util/StringsTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaStringConverter.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java, org.eclipse.xtext/src/org/eclipse/xtext/conversion/impl/STRINGValueConverter.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/DerivedStateAwareResource.java, releng/pom.xml
This fixes a regression introduced with Xtext 2.15. The entire logic for String escaping does perform better now and is easier to reuse. This is achieved by introducing the JavaStringConverter.
The commit does also contain a bunch of fixed warnings.
=> [#950] Fixed regression in Strings.convertFromJavaString

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
- Added test cases to cover setting of entries that have other
attributes then version alone.
- Fix MergeableManifest to support given test cases.
- Refactor existing test cases a bit to avoid uneccessary
"Collections.singleton"
=> #953: Support setting of entries with attributes.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeCrossrefProposalProvider.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IdeCrossrefProposalProvider.java
The reference kind can already be set when the proposal is created at this place because we know the proposal is created for a CrossReference.
This avoids having to do more complex checking later on in the auto complete flow to set the kind.
=> Set reference kind when we know it should be set

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/GeneratorNodePerformanceTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodePerformanceTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java
Time spend for the performance test  
```
Lines 800_000 // Before x sec - after 4.6 sec
Lines  80_000 // Before 89 sec - after 0.43 sec
Lines  40_000 // Before 20 sec - after 0.32 sec
Lines  20_000 // Before 5 sec - after 0.25 sec
Lines  10_000 // Before 1.8 sec - after 0.25 sec
```
=> [trace] Improved implementation for GeneratorNodeProcessor.Context

org.eclipse.xtext.util/src/org/eclipse/xtext/util/concurrent/IReadAccess.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/concurrent/IWriteAccess.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/concurrent/WrappingCancelableUnitOfWork.java
The suggested type for `readOnly()` is a `CancelableUnitOfWork` and several places ([here](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/resource/OutdatedStateManager.xtend#L63) and [here](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java#L506)) check if the `IUnitOfWork` is a `CancelableUnitOfWork`. It isn't because `tryReadOnly()` wraps the `IUnitOfWork` in a lambda.
This patch modifies `tryReadOnly()`, `tryPriorityReadOnly()` and `tryModify()` so that they wraps `work` in a `CancelableUnitOfWork` if work is a `CancelableUnitOfWork`.
A prettier way would be to add an overloaded `try...` that takes a `CancelableUnitOfWork` as argument instead of a `IUnitOfWork`, …
=> Use try read only

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/JavaVersionTest.java, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
[eclipse/xtext#1182] added support for java 11 as target
=> [eclipse/xtext#1182] added support for java 11 as target

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
Needed to fix failing UI tests (Actually the JUnit 5 minimal version is 5.0.0 instead of 5.1.0 for eclipse oxygen).
=> Fix ui tests

org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinker.java
Check the case that c == superType, which is always the case when called
from findInstantiableCompatible, and occasionally for calls from
findSubTypeInEPackage
=> [performance] Improve isInstantiatableSubType

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
To avoid reformatting we maintain the separators (e.g. line breaks) with
the entries (e.g. inside the required bundles entry).
=> #1018 Maintain existing formatting.

gradle/upstream-repositories.gradle
=> workaround for jcenter maven central sync is too slow

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
Filter all entries from "Require-Bundle", "Export-Package" and
"Import-Package" entries that are empty to fix manifest files that are
invalid in this regard.
=> [#1038] Filter bad entries when read in MANIFEST.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/index/ResourceDescriptionStrategyFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/index/ResourceDescriptionStrategyFragment.java
such that the @Exported annotations of any super grammars are used as well. This way it behaves more like the ValidatorFragment2, where validations of super grammars are also taken into account.
=> Make ResourceDescriptionStrategyFragment aware of super grammars

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend
Delete on exit doesn't work if the folder is not empty. Since we don't
remove the individual files the folder doesn't get deleted.
=> Actually delete LSP test folder after test

org.eclipse.xtext.tests/build.gradle, org.eclipse.xtext.tests/src/org/eclipse/xtext/GenerateAllTestLanguages.mwe2
[#1066] get rid of org.eclipse.xtext.ecore.EcoreSupport again
=> [#1066] get rid of org.eclipse.xtext.ecore.EcoreSupport again

org.eclipse.xtext/src/org/eclipse/xtext/build/BuildContext.xtend, org.eclipse.xtext/src/org/eclipse/xtext/build/BuildRequest.xtend, org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend, org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.xtend, org.eclipse.xtext/src/org/eclipse/xtext/build/Source2GeneratedMapping.xtend
Mainly replace spaces by tabs. Sources are to a high grade already tab-indented.
=> Cleanup WS formatting in package org.eclipse.xtext.build

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest2.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CompletionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest2.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/ChangeConverter.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/ChangeConverter.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/IRenameService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/IRenameServiceExtension.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
- delegate to rename language of the declaration of the renamed target
- allow to trigger rename with caret right after the identifier
- support versioned documents
Closes #917, closes #916 and closes #1072
=> [LS] overhauled rename service

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
Dependency versions are obsolete since they are managed by the BOM.
=> [#1076] Remove BOM managed versions

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/LspExtensionTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/LspExtensionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerAccess.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerAccess.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
From now on, it is possible to read the content of the Xtext
index from a LS access.
Closes #1067.
=> GH-1067: Exposed the Xtext index to the LS access.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
There was an add, but no remove effectively creating a memory leak by
keeping dead listeners around.
=> Added removeBuildListener to WorkspaceManager

org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IncrementalBuilder.java
When a resource is loaded for the first time, there is no need to unload it between pre-indexing and build
=> [lsp] some build performance tuning

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/IResourceRelocationStrategy.java
In more detail, by overriding this method an implementation may explicitly demand for relying on the persisted resource index, if possible.
Currently, this is only possible (in Eclipse) by registering specialized implementations into the global language independent injector.
=> [refactoring] introduced default method in 'IResourceRelocationStrategy' allowing to switch to persisted index

org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/AssertableDiagnostics.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/DiagnosticTreeIterableTest.java
DiagnosticTreeIterator always returns the same iterator when you call
iterator(). This means it can't be iterated twice.
The Iterable interface does not force you to return a new Iterator every time but this is common practice. If this change doesn't get accepted because of this reason, it would be nice to at least have a comment on iterator().
=> Make DiagnosticTreeIterator return a new iterator every time

org.eclipse.xtext.util/META-INF/MANIFEST.MF
Fixes eclipse/xtext#1398 and eclipse/xtext-lib#111
=> update to guava 27.1

Jenkinsfile
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> [eclipse/xtext#1481] Delete org/eclipse/[xtext|xtend] from local .m2

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
[eclipse/xtext-eclipse#1102] [wizard] eclipse launch - set "Clear Configuration" to true
=> [eclipse/xtext-eclipse#1102] [wizard] eclipse launch - set "Clear Configuration" to true

1-gradle-build.sh, CBI.Jenkinsfile
Disable Gradle daemon, since a new container for each build is
spawned and the daemon can't be reused anyway.
Remove CPU resource constraint, since default is sufficient.
=> [eclipse/xtext#1431] Enhance container support

org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/TemporaryFolder.java
[eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile
=> [eclipse/xtext#1432] fixed implementation of TemporaryFolder.createTempFile

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SourceFolderCustomImplTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SourceFolderDefaultImplTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/SourceFolderCustomImplTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/SourceFolderDefaultImplTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ProjectManager.java, org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileProjectConfig.xtend, org.eclipse.xtext/src/org/eclipse/xtext/workspace/IProjectConfig.java, org.eclipse.xtext/src/org/eclipse/xtext/workspace/ISourceFolder.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/FileProjectConfig.java
While implementing LSP support for our Xtext language based on xtext.ide packages, we found some issues. Some of those we would like to address in this PR, regarding IProjectConfig and ISourceFolder:
* missing output folders in IProjectConfig (actually, we only need one, but others might need more)
* excluding some files within source folders (happens e.g. when source and output folders are the same, see e.g. TypeScript)
Notes:
* I am not sure whether the new interface `IOutputFolder` is the best choice. Actually, I would prefer to rename `ISourceFolder`, but I guess this wouldn't be a good idea for xtext API continuity.
* The method `ResourceStorageFacade#computeOutputPath(StorageAwareResource)` sounds like it does something with output paths, although it looks like it is computing a …
=> Extend IProjectConfig and related interfaces

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1279] use orbit simrel alias directly
=> [eclipse/xtext#1279] use orbit simrel alias directly

org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/hierarchy/DefaultHierarchyNodeReference.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java
[eclipse/xtext-lib#224] Stable method order when using Delegate annotation
=> [eclipse/xtext-lib#224] Stable method order when using Delegate

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[eclipse/xtext-core#1082] update to lsp4j 0.8.0
=> [eclipse/xtext-core#1082] update to lsp4j 0.8.0

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/AbstractNode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/GrammarElementsInterner.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/NodeModelBuilder.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/serialization/DeserializationConversionContext.java
The node model contains nodes derived from AbstractNode.  An
AbstractNode has an array describing its grammar elements.  This array
is often identical for many AbstractNodes.  There can be millions of
nodes in a node model so it makes sense to remove the duplicate arrays.
This GrammarElementsInterner tries to reuse an interned version of
such an array wherever possible.  In particular, now we also intern
grammar elements when they are created during the load of a node model
from the node model cache.
Testing this modification on a largisch project showed that the
execution time of a clean build that accesses the node model cache
reduces by around 10%.
=> Intern grammar elements when nodes are created from the cache

gradle/versions.gradle, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/PartialSerializationTestLanguageStandaloneSetup.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/PartialSerializationTestLanguageStandaloneSetup.java
[eclipse/xtext#1537] bootstrap against 2.19.0
=> [eclipse/xtext#1537] bootstrap against 2.19.0

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1538] use eclipse 2019-12 in target
=> [eclipse/xtext#1538] use eclipse 2019-12 in target

org.eclipse.xtext/build.gradle
- Add xtext32.png to the build.gradle file.
=> [https://github.com/eclipse/xtext/issues/1486]

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/FilesTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Files.java
The previous behavior does not remove the parent folder when its has no
file inside and the "deleteParentFolder" argument is true.
The behavior of the function is updated to delete the parent folder as
expected.
Additionally, the recursive algorithm is replaced by an iterative
algorithm in order to make it more robust.
Signed-off-by: Stéphane Galland <galland@arakhne.org>
=> [util] Fixing the behavior of the cleanFolder function in Files class.

org.eclipse.xtext.ide.tests/xtext.ide.tests (xtend).launch, org.eclipse.xtext.ide.tests/xtext.ide.tests.launch, org.eclipse.xtext.tests/xtext.tests (xtend).launch, org.eclipse.xtext.tests/xtext.tests.launch
These changes were automatically applied to the launch configurations on
a fresh workspace setup.
=> [eclipse/xtext#1568] Remove Buildship classpath container

.gitpod.yml
Seems like the Java LS is not ready to handle our mix of Xtend and
Java, even when we build with Gradle. Having a Java-only build
doesn't make to much sense.
=> [gitpod] removed .gitpod.yml again

org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/XtendXtext2EcorePostProcessor.java
log deprecation warning if xtend based postprocessor is used
=> log deprecation warning if xtend based postprocessor is used

org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/StateBasedContainer.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/StateBasedContainerManager.java
before any other filter operation
there is a performance benefit, when first exclude all irrelevant
resources before considering their IEObjectDescriptions
Signed-off-by: gabrield <d.gabriel@bachmann.info>
=> [eclipse/xtext-core#1252] filter for contained resource descriptions

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
This PR generates in the POMs of the projects created by the wizard the mwe2Version variable that is used for running the MWE2 generator from Maven, instead of hardcoding the version. This way, the developer can simply update that variable when he/she also updates the Xtext version in the parent POM.
Similarly, the `.target` file is generated by using `config.xtextVersion.mweVersion`; this has no effect on the generated `.target` file but at least it should be easier to keep the generation of the `.target` file consistent.
=> Use mwe2version in POMs and target platform, instead of hard-coding

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
This PR generates in the POMs of the projects created by the wizard the mwe2Version variable that is used for running the MWE2 generator from Maven, instead of hardcoding the version. It does so only on Tycho-based projects.
I think it's better to generate the property right after the property for the xtext version (instead of later in the Tycho section).
see also #1305 
=> Use mwe2version in Tycho-based POMs instead of hard-coding

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.java
[#1318] added missing xtend.lib dependency to make sure AA can run
=> [#1318] added missing xtend.lib dependency to make sure AA can run

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/IndexOnlyProjectTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/IndexOnlyProjectTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.java, org.eclipse.xtext/src/org/eclipse/xtext/workspace/IProjectConfig.java
Currently, the flag `indexOnly` from class `BuildRequest` is read in `IncrementalBuilder` but never set in production code (i.e. only set in some test code). This PR introduces the default interface method `IProjectConfig#isIndexOnly()` which can be overridden by client code. The result of this method will later be used to create the `BuildRequest` and then be respected by the incremental builder. This way, this flag allows e.g. library projects which neither have to be validated nor have to be generated.
=> Make use of already implemented flag indexOnly and set it in IProjectConfig

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/AbstractRequest.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/ReadRequest.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java, org.eclipse.xtext/src/org/eclipse/xtext/service/OperationCanceledManager.java
The `LanguageServerImpl` uses the pattern of implementing methods from `org.eclipse.lsp4j` e.g. ` org.eclipse.lsp4j.services.TextDocumentService` and returns futures directly, see here:
```java
@Override
public CompletableFuture<List<Either<Command, CodeAction>>> codeAction(CodeActionParams params) {
return requestManager.runRead((cancelIndicator) -> codeAction(params, cancelIndicator));
}
```
When an exception is thrown during the call to `codeAction(...)` this exception gets visible when joining the future, e.g. by calling `future.get()`. Since `lsp4j` does not do this, those exceptions are lost and never show up. Hence, the `RequestManager` should anticipate this and log exceptions itself.
=> Log Exceptions thrown in futures created by the RequestManger

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.java
=> [#1272] Add missing 'See' prefix to the url in javadoc comments.

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/LineFilterOutputStreamTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/LineFilterOutputStream.java
[#1328] marked obsolete LineFilterOutputStream as deprecated
=> [#1328] marked obsolete LineFilterOutputStream as deprecated

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Document#getLineContent returns the '\r' of '\r\n' on windows. This
leads to a failing test. But the line content should explicitly NOT
return the newline marker. Hence fixing the implementation to fix the
test.
=> [eclipse/xtext#1455] Resolve test failure in DocumentTest.

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/EMFGeneratorFragment2Test.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/EMFGeneratorFragment2Test.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
- Improve the trimMultiLineComment method to properly handle the /**,
/*******, **/ and ****************/ symbols.
- Implement corresponding EmfGeneratorFragment2Test test cases.
=> [#1345] Improve EMFGeneratorFragment2 fileHeader handling.

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/EMFGeneratorFragment2Test.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/EMFGeneratorFragment2Test.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
- to be able to override that method in derived classes.
=> Convert EMFGeneratorFragment2.trimMultiLineComment to an instance method

org.eclipse.xtext.util/src/org/eclipse/xtext/util/ReplaceRegion.java
`org.eclipse.xtext.util.ReplaceRegion` does not provide the methods `hashCode()` or `equals()`. This is a problem when using for instance `org.eclipse.xtext.ide.editor.contentassist.ContentAssistEntry`. `ContentAssistEntry` uses Xtend annotation `@EqualsHashCode` and also defines a field of type `ArrayList<ReplaceRegion>`. Since `ReplaceRegion` lacks method `hashCode()`, the hash code method of `ContentAssistEntry` is unreliable and instances of `ReplaceRegion` cannot be used e.g. in HashSets.
Please let me know if you have suggestions to improve the implementations of `hashCode()` and `equals()`.
=> Add hashCode() and equals() to ReplaceRegion

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/StorageAwareResource.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/StorageAwareResource.java
[eclipse/xtext#1651] made error handling in StorageAwareResource null-safe
=> [eclipse/xtext#1651] made error handling in StorageAwareResource null-safe

org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/BasicNodeIterable.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/BasicNodeIterableTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/BasicNodeIterator.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/BasicNodeIteratorTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/util/NodeIterableTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/util/NodeIteratorTest.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/BasicNodeIterable.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/BasicNodeIterator.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeIterable.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeIterator.java
Throw NullPointerException if null is passed to NodeIterator constructor
to prevent iterator state where hasNext() and hasPrevious() always
return true, but getNext() and getPrevious() always return null.
Signed-off-by: Robert Lewis <rablewis@algo-pop.com>
=> [#1262] Prevent infinite loop with NodeIterator.

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/AbstractRequest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/ReadRequest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestCancelIndicator.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
The request manager was prone to races when a runnable was already in progress and a new write request was submitted in parallel. The runnable future would immediately be considered to be cancelled but the runnable would still continue to be processed.
Also there was a chance of deadlocks when a custom LSP command used the request manager to submit a modifying write request.
closes #622
=> [#622] Improved concurrency behavior of RequestManager

org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CompletionTest.java
committed missing downstream xtend-gen
=> committed missing downstream xtend-gen

org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/contentassist/antlr/PartialIndentationAwareUiTestLanguageContentAssistParser.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/contentassist/antlr/PartialPartialContentAssistTestLanguageContentAssistParser.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/contentassist/antlr/PartialPartialSerializationTestLanguageContentAssistParser.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/contentassist/antlr/PartialRenameTestLanguageContentAssistParser.java, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/contentassist/antlr/PartialTestLanguageContentAssistParser.java, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/fileAware/ide/contentassist/antlr/PartialFileAwareTestLanguageContentAssistParser.java, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/nestedRefs/ide/contentassist/antlr/PartialNestedRefsTestLanguageContentAssistParser.java, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/PartialNoJdtTestLanguageContentAssistParser.java, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/xtextgrammar/ide/contentassist/antlr/PartialXtextGrammarTestLanguageContentAssistParser.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/templates/CodetemplatesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/templates/CodetemplatesGeneratorFragment2.java, org.eclipse.xtext.xtext.ide/src-gen/org/eclipse/xtext/xtext/ide/contentassist/antlr/PartialXtextContentAssistParser.java
[eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers
=> [eclipse/xtext-core#1418] removed redundant superinterface from generated ca parsers

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.java
[eclipse/xtext-core#1318] fixed dependencies of file template active annotation in wizard
=> [eclipse/xtext-core#1318] fixed dependencies of file template active annotation in wizard

org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResource.java
[#1458] made XtextResource.getParser more easily customizeable
=> [#1458] made XtextResource.getParser more easily customizeable

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.java
- Modify the GrammarAccessFragment2 to use
JavaFileAccess.DONT_IMPORT_NESTED_TYPES flag in order to avoid the
generation of unnecessary import and warnings.
=> [#269] Ensure no unnecessary import is generated for GrammarAccess.

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/terminalrules/DefaultTerminalConverterTest.java
[eclipse/xtext#1738] use java.text.SimpleDateFormat instead of com.ibm.icu.SimpleDateFormat
=> [eclipse/xtext#1738] use java.text.SimpleDateFormat instead of com.ibm.icu.SimpleDateFormat

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensionsTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.java
[eclipse/xtext#1738] avoid usage of icu.Transliterator
=> [eclipse/xtext#1738] avoid usage of icu.Transliterator

org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/build.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/build.properties, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
[eclipse/xtext#1738] removed no longer needed icu dependency
=> [eclipse/xtext#1738] removed no longer needed icu dependency

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/XtextRuntimeModule.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextLinker.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/IXtext2EcorePostProcessor.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/XtendXtext2EcorePostProcessor.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated
=> marked xpand/xtend(1) depending XtendXtext2EcorePostProcessor as deprecated

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/ExecutorServiceProvider.java
PS https://github.com/eclipse/xtext-core/pull/1442#discussion_r407526478 for details regarding this fix.
Signed-off-by: nbhusare <neerajbhusare@gmail.com>
=> Fixed the synchronization strategy in ExecutorServiceProvider

org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/noJdt/formatting2/NoJdtTestLanguageFormatter.xtend, org.eclipse.xtext.testlanguages/xtend-gen/org/eclipse/xtext/testlanguages/noJdt/formatting2/NoJdtTestLanguageFormatter.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/SerializerReplacementCalculationTest.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/impl/Serializer.java
- Improve the serializeReplacement implementation by modifying the
ReplaceRegion length calculation so that it takes not only the
ICompositeNode.getTotalLength() into account, but considers if the new
text contains additional whitespaces and the old text is also followed
by white spaces, than the whitespaces contained by the original document
is also consumed by the quickfix.
=> [https://github.com/eclipse/xtext-eclipse/issues/1221] Serializer.

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextFormatterTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensions2Test.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/XtextFormatterTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/GrammarAccessExtensions2Test.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting/impl/FormattingConfigBasedStream.java
- Modify the FormattingConfigBasedStream to handle the different line
endings properly.
- Implement corresponding XtextFormatterTest and
GrammarAccessExtensionsTest test cases.
=> [#1443] Fix XtextFormatter behaviour on different line endings.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java
````
junitSupport = {
generateStub = false
}
````
No stub is generated
````
junitSupport = {
generateStub = true
}
````
JUnit stub is generated in Xtend
````
junitSupport = {
generateStub = true
generateXtendStub = true
}
````
JUnit stub is generated in Xtend
````
junitSupport = {
generateStub = true
generateXtendStub = false
}
````
JUnit stub is generated in Java
Signed-off-by: nbhusare <neerajbhusare@gmail.com>
=> Added support for Java stub generation in the JUnitFragment

Jenkinsfile
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [eclipse/xtext#1769] Removed jnlp image name from pod template

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/InjectionExtensionNested2Test.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/InjectionExtensionNestedTest.java
The functional change was implemented/suggested by Christian Dietrich.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=563136
Current restriction is, that multiple @InjectWidth (1 on outer, 1 on
inner class) will not work. Only one is allowed.
Signed-off-by: Frank Benoit <frank.rene.benoit@gmail.com>
=> [#1509] Fix InjectionExtension for nested test classes

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageWritable.java
The methods in question had a return type `Object` but the return value was never used.
Updated to return `void` instead.
=> API cleanup after Xtend2Java

org.eclipse.xtext.tests/.settings/org.eclipse.xtend.shared.ui.prefs, org.eclipse.xtext/.settings/org.eclipse.xtend.shared.ui.prefs
removed obsolete org.eclipse.xtend.shared.ui.prefs
=> removed obsolete org.eclipse.xtend.shared.ui.prefs

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Subsequent unassigned actions are not allowed if there was already a
current instance present.
=> Improved grammar validation in the context of unassigned rule calls

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/CommentFormatterTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/CommentWithSpacesFormatterTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/CommentWithSpacesFormatterTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/HiddenRegionReplacer.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/MultilineCommentReplacer.java
Replaces https://github.com/eclipse/xtext-core/pull/199 (which was on a fork instead of a branch)
=> Fixed spaces after ML comments in format

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
[eclipse/xtext#1863] respect java version in generated launch config
Fixed eclipse/xtext#1863
=> [eclipse/xtext#1863] respect java version in generated launch config

gradle/maven-deployment.gradle
[eclipse/xtext#1652] Use https instead of git URL for SCM connection
Harmonized newline at eof in gradle and poms
=> [eclipse/xtext#1652] Use https instead of git URL for SCM connection

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1885] use 2021-03 in wizard
DO NOT merge yet, as 2021-03 is not available yet
=> [eclipse/xtext#1885] use 2021-03 in wizard

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
The release-prepare-branches can also create a Beta release for testing
purpose. The version string is then 'x.x.x.Beta'. This was not
considered properly by the test.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> Consider Beta release pattern in version string

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
Following platform upgrade of GSON from Bug#569966.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [eclipse/xtext#1916] Upgrade GSON to 2.8.6

org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/fileAware/formatting2/FileAwareTestLanguageFormatter.java
fixed npe in formatter in tests
=> fixed npe in formatter in tests

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensions2Test.java
[eclipse/xtext-core#1666] added testcase for special ML_COMMENT
=> [eclipse/xtext-core#1666] added testcase for special ML_COMMENT

org.eclipse.xtext.util/META-INF/MANIFEST.MF, releng/releng-target/xtext-core.target.target
Update Google Guava version from 27.1.0 to 30.1.0
Signed-off-by: miklossy <miklossy@itemis.de>
=> https://github.com/eclipse/xtext/issues/1862 Guava 30.1.0

org.eclipse.xtext/src/org/eclipse/xtext/mwe/PathTraverser.java
[eclipse/xtext#1953] print  broken zip file when traversing archive fails
=> [eclipse/xtext#1953] print  broken zip file when traversing archive fails

releng/releng-target/xtext-core.target.target
[eclipse/xtext#1927] re-adjust bootstrapping targets for mwe(2)
=> [eclipse/xtext#1927] re-adjust bootstrapping targets for mwe(2)

org.eclipse.xtext/src/org/eclipse/xtext/generator/OutputConfiguration.java
Signed-off-by: miklossy <miklossy@itemis.de>
=> Fixing a typo in javadoc of the OutputConfiguration class.

org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultResourceDescriptionManager.java
performance optimization for isAffected with a large number of imported names
=> performance optimization for isAffected with a large number of imported names

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/folding/AbstractFoldingRangeProviderTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/folding/FoldingRangeProviderTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/FoldingTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/DefaultFoldingRangeAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/DefaultFoldingRangeProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/FoldingRange.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/FoldingRangeKind.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/IFoldingRangeAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/IFoldingRangeProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/folding/FoldingRangeService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/FoldingConfiguration.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
This solution should be easily adaptable for the eclipse/xtext-eclipse repo. The API is mostly based on the original implementation for Eclipse.
This should close #897
=> [#897] Folding Support for LSP

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
filter hidden nodes for value conversion of enums. 
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=574721
=> filter hidden nodes for value conversion of enums. 

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/XtextResourceTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResource.java
clear caches on updateInternalState
Fixes eclipse/xtext-eclipse#1697
=> clear caches on updateInternalState

org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/junit5/ComposedInject.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/junit5/ComposedInjectAnnotationTest.java
Use the JUnit Platform annotation retrieval to also look at super
interfaces, composed interfaces etc. of the test class.
JUnit Platform 1.y.z corresponds to JUnit Jupiter 5.y.z, that's why the
platform range [1,2) should fit well to the existing Jupiter range [5,6)
in the manifest.
Signed-off-by: Michael Keppler <Michael.Keppler@gmx.de>
=> Make @InjectWith meta-annotation capable (fix #1789)

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/HiddenRegionFormatting.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/HiddenRegionFormattingMerger.java
mergeValuesFrom in HiddenRegionFormatting now updates the priority
The calculation of strategy can no longer cause overflows
Signed-off-by: Lawrence Goossens <lawrence.goossens@sigasi.com>
=> Fix hidden region formatting priorities (fix #1798)

org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java
Make QualifiedName.USE_INTERNING writable (using reflection)
Fixes #1787
=> Make QualifiedName.USE_INTERNING writable (using reflection)

org.eclipse.xtext.xtext.generator/build.gradle
[eclipse/xtext#1976] pin explicit transitive deps in xtext.xtext.generator
=> [eclipse/xtext#1976] pin explicit transitive deps in xtext.xtext.generator

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/AbstractNode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/CompositeNode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/CompositeNodeWithSemanticElement.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/CompositeNodeWithSemanticElementAndSyntaxError.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/CompositeNodeWithSyntaxError.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/HiddenLeafNode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/HiddenLeafNodeWithSyntaxError.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/LeafNode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/LeafNodeWithSyntaxError.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/RootNode.java
Signed-off-by: Mark Sujew <mark.sujew@typefox.io>
In one of our projects, we override the `NodeModelBuilder` to create custom leaf nodes (which don't inherit from the default `LeafNode` class). However, since the `NodeType` enum, and the `write`/`readData` methods were package private, we were not able to override them, even though the serializer needs them to be overriden.
This change just changes them to be accessible by downstream classes which directly inherit `AbstractNode`.
=> Expose serialization methods on AbstractNode

org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.java
As a followup of https://github.com/eclipse/xtext-core/pull/1807, do not generally downgrade the error to debug log in the Indexer, but allow subclassing of Indexer.ResolvedResourceDescription to remove the error logs if desired (or extend it in any other way) without the need to reimplement the full addToIndex method.
=> Add protected method for subclassing Indexer.ResolvedResourceDescription

org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.java
Write binary models even if no GeneratorDelegate is provided. The binary models can be used when demand-loading resources during the incremental build, regardless of if there is a GeneratorDelegate, thus, persist them at the beginnig of the generate method.
=> Always write binary models

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseUsageDetector.java
Fix XbaseUsageDetector for overriden rules, where the gramar is a different one than org.eclipse.xtext.xbase.Xtype. Instead of the EPackage URI of the rule.
=> XbaseUsageDetector for overriden rules

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/validation/AssertableDiagnostics.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/AbstractConcreteSyntaxValidationTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/AbstractValidatorTester.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ConcreteSyntaxValidationTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/DiagnosticTreeIterableTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTester.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTesterTest.java
[eclipse/xtext#1854] Move AssertableDiagnostics to xtext.testing
Signed-off-by: Edmundo Lopez Bobeda <edmundo@lopezbobeda.net>
=> [eclipse/xtext#1854] Move AssertableDiagnostics to xtext.testing.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.java
used for text edits in the same way that we allow for configuration for
the other resource sets created by the Language Server
=> Allow configuration by custom LS implementations of the live resourceSet

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentSymbolTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/HierarchicalDocumentSymbolTest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/DocumentSymbolConfiguration.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Rubén Porras Campo <pcr@avaloq.com>
=> Fix typo in class name DocumentSymbolConfiguration

org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs
added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs
=> added missing org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.core.resources.prefs

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/quickfix/AbstractIdeQuickfixTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/quickfix/TestLanguageQuickfixTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/CodeActionTest.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/quickfix/TestLanguageQuickFixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/AbstractDeclarativeIdeQuickfixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolutionAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/IQuickFixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/ITextModification.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/TextEditAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/QuickFixCodeActionService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/ChangeConverter2.java
In addition, improve naming of variables in the existing API to use
diagnostics for org.eclipse.lsp4j.Diagnostic instead of issues and
errors, and resolutions for DiagnosticResolution instead of issues in
the DiagnosticResolutionAcceptor
=> Add API for textual Code Actions

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/quickfix/TestLanguageQuickFixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/AbstractDeclarativeIdeQuickfixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolutionAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/ISemanticModification.java
contained in the diagnostic.
Also, add one convenience method to create textual QFs which just
replace the region of the diagnostic with a new text.
Signed-off-by: Rubén Porras Campo <Ruben.PorrasCampo@avaloq.com>
=> Extend the Quickfix API to support semantic QFs that use the data

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DefinitionTest.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/rename/TestLanguageRenameService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolService.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/EObjectAtOffsetHelper.java
Otherwise the client will think some elements point to definitions which do not exist, and will for example jump to the beginnig of a comment or string when the user press Control-Click somewhere in one of these, which is very confusing.
=> Only return resolved cross references

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/quickfix/AbstractIdeQuickfixTest.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/AbstractDeclarativeIdeQuickfixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/IQuickFixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerAccess.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/ICodeActionService2.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/QuickFixCodeActionService.java
only if there are fix methods for the given diagnostic. This might saves
the resource load operation, which can be expensive.
=> Improve code actions performance by loading the document on demand

org.eclipse.xtext/src/org/eclipse/xtext/build/BuildRequest.java, org.eclipse.xtext/src/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.java, org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/SourceLevelURIsAdapter.java
by doing that we increase the performance of the
BuildContext#executeClustered because it will be possible to use binary
models from resources which has already been built and stored.
Signed-off-by: rubenporras <Ruben.PorrasCampo@avaloq.com>
=> Storing a binary resource removes its URI from the SourceLevelURIs set

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java
so that it can be used by quickfixes.
Signed-off-by: Rubén Porras Campo <Ruben.PorrasCampo@avaloq.com>
=> Propagate the Issue Data to the Diagnostic Data

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java
The error is logged but the method still returns a (null) value. This allows the server to return a CodeAction to the client, that this can inspect and discard (because no editAction is set). Otherwise the client will wait for the server and show it like that on the UI, which does not create a good user experience.
=> Return a WorkspaceEdit even if an exception is thrown

org.eclipse.xtext.ide.tests/.settings/org.eclipse.jdt.core.prefs
[eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs
=> [eclipse/xtext#2099] added missing org.eclipse.jdt.core.prefs

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/IndexOnlyProjectTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SemanticTokensTest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/SemanticTokensFullConfiguration.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
also, include a small fix to IndexOnlyProjectTest to avoid a "possible NPE" marker given by the JDT Null Pointer Analysis.
Signed-off-by: rubenporras <Ruben.PorrasCampo@avaloq.com>
=> Improve SemanticTokensFullConfiguration to avoid text comparison

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/codemining/CodeMiningFragment.java
[eclipse/xtext-eclipse#1963] remove Class.forName guard for code minings
=> [eclipse/xtext-eclipse#1963] remove Class.forName guard for code minings

org.eclipse.xtext.tests/src/org/eclipse/xtext/workspace/FileSourceFolderTest.java
see https://github.com/eclipse/xtext-eclipse/issues/1997
This introduces a test for `FileSourceFolder` existing behavior
=> FileSourceFolderTest
