org.eclipse.xtext.tests/src/org/eclipse/xtext/mwe/UriBasedReaderTest.java
=> Fix UriBasedReaderTest

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
ATTENTION: this (mutually) depends on https://github.com/eclipse/xtext-eclipse/pull/19
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=494176
=> 494176: Warning: The file "plugin.xml" does not exist in the workspace

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/IFileSystemScanner.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/IFileSystemScanner.java
This fixes the uri en- and decoding problems on windows.
=> improved uri handling on windows

org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/serialization/SerializationUtilTest.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/serialization/SerializationUtil.java
=> (De)Serializing the NodeModel with IResourceStorageFacade is not working if transient features involved

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Covered by test CliWizardIntegrationTest
=> [#76] Upgrade to Tycho 0.25.0

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> [#79] Upgrade Eclipse & MWE p2 repository URLs

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
=> [431435] Bind generated EPackage and EFactory

org.eclipse.xtext/src/org/eclipse/xtext/validation/CheckType.java
[435441] Added JavaDoc to CheckType Enum
=> [435441] Added JavaDoc to CheckType Enum

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
[482110] fixed AbstractFormatter2.shouldFormat
=> [482110] fixed AbstractFormatter2.shouldFormat

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
=> [#67] Mark exported test packages as internal

gradle/eclipse-project-layout.gradle, gradle/java-compiler-settings.gradle, org.eclipse.xtext.testing/build.gradle, org.eclipse.xtext.tests/build.gradle, org.eclipse.xtext.util/build.gradle, org.eclipse.xtext/build.gradle
Consistent use of tabs instead of spaces
Use single whitespace between brackets
=> [format] Streamlined whitespaces

org.eclipse.xtext.testlanguages.ide/.classpath, org.eclipse.xtext.testlanguages/.classpath, org.eclipse.xtext.tests/.classpath, org.eclipse.xtext.xtext.generator/.classpath, org.eclipse.xtext/.classpath
=> [#5] Ignore optional compile problems on *-gen source folders

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormatterReplacementsTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormatterReplacementsTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java
=> fixed #14: [formatter2] honor FormatterRequest.allowIdentityEdits

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
=> [#108] Ecore2Xtext use new formatter fragment

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java
=> [378980] Refactored calls on deprecated API

org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/plugin.properties
=> [502879] Streamlined plugin metadata

org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/EmitterNodeUtil.java
this is a fixup for cb9981d14cc279cb0433b63c9c88f8ebf20ba739
=> fix eclipse/xtext-extras#63 broken serializer tests

org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/BacktrackingSemanticSequencer.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/ISemanticNodeProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/SemanticNodeProvider.java
=> [serializer/performance] avoid redundant traversal of node model

org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/NfaUtil.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarConstraintProvider.java
Implemented new algorithms for computing upper and lower bounds in GrammarConstraintProvider.
=> [serializer] Improved performance of bounds computation

org.eclipse.xtext/src/org/eclipse/xtext/parser/antlr/IReferableElementsUnloader.java
=> Change default binding of IReferableElementsUnloader to GenericUnloader

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
add .testing to dependencies of ui tests
=> add .testing to dependencies of ui tests

gradle/eclipse-project-layout.gradle, org.eclipse.xtext.util/plugin.properties
readded plugin.properties. fixes #154
=> readded plugin.properties. fixes #154

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
[WEB][Wizard][Generator] Update JS Libary Versions. Fixed #156
=> [WEB][Wizard][Generator] Update JS Libary Versions. Fixed #156

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
Signed-off-by: Karsten Thoms karsten.thoms@itemis.de
=> [#118] Improve generated test code

.gitignore, .settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.ide.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.ide/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.testing/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.testlanguages.ide/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.testlanguages/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.tests/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.util/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xtext.generator/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext.xtext.wizard/.settings/org.eclipse.buildship.core.prefs, org.eclipse.xtext/.settings/org.eclipse.buildship.core.prefs
connection.project.dir changed to composite build location in new
umbrella project
value 'containers' added by Buildship
=> Gradle composite

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/templates/CodetemplatesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/templates/CodetemplatesGeneratorFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
fixed broken generator regarding !== and ===. fixes #189
=> fixed broken generator regarding !== and ===. fixes #189

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ecore/SubTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/AbstractTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/ConcreteTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/InheritanceTest2Language.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/InheritanceTest3Language.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/grammarinheritance/InheritanceTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/IgnoreCaseImportsTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/IgnoreCaseNamespacesTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/indentation/IndentationAwareTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/parameters/NoParametersTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/parameters/ParametersTestLanguageEx.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/parameters/TwoParametersTestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/parsetree/reconstr/Bug302128TestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Bug285140TestLanguage.xtext, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/DataTypeRuleWithEnumResultTestLanguage.xtext
=> Added missing Override annotations

org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceKey.java
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
=> Fixed typo in PreferenceKey.java

build.gradle, gradle/bootstrap-setup.gradle, gradle/eclipse-project-layout.gradle, gradle/xtend-compiler-settings.gradle
* Use build result from xtend-bootstrap job for Xtend compiler
* Added `skipXtendCompiler` option
=> Improve Xtend bootstrap

org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/NfaUtil.java
=> [#212] Refactored to avoid JDT 508834

gradle/versions.gradle, org.eclipse.xtext.testlanguages/build.gradle, org.eclipse.xtext/build.gradle
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
=> [Wizard] General: Gradle Tests dont work #224

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=479196
=> 479196: AntlrToolFacade always downloads antlr-generator in Maven build

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
Task-Url: https://github.com/eclipse/xtext-core/issues/230
Closes #230
=> 230: Junit4Fragment2 added dependencies for .tests project

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> fixed #265: Create pom.xml that installs Xtend Debug Info

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/CodeConfig.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/GeneratedJavaFileAccess.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/annotations/GeneratedClassAnnotation.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/annotations/IClassAnnotation.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/annotations/SingletonClassAnnotation.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/annotations/SuppressWarningsAnnotation.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/GeneratedJavaFileAccess.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/annotations/GeneratedClassAnnotation.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/annotations/IClassAnnotation.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/annotations/SingletonClassAnnotation.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/annotations/SuppressWarningsAnnotation.java
Respect @Repeatable property of Annotations in the Xtext Generator. Fixes #270
=> Respect @Repeatable property of Annotations in the Xtext Generator. 

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/PolymorphicDispatcherTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/PolymorphicDispatcher.java
This fix prevents exceptions such as "IllegalArgumentException:
Comparison method violates its general contract" by not sorting the list
of methods at all. Since the method selection algorithm scans the
complete list of methods, the order of the list does not impact the
algorithm's outcome. 
The fix does not change the precedence of methods since the
implementation of compare(method1, method2) is kept the same.
However, this bug taught us that compare(m1, m2) is not suitable to
establish a total order among a list of methods and that 
compare(m1, m2)==0 && compare(m2, m3)==0 
does NOT imply compare(m1, m3)==0.
Example:
m1(A a), m2(B b), m3(C c), class A{}, class B{}, class C extends A{}
This observation required another change: When scanning the list of
methods for candidates, it does not …
=> fixed #238 in PolymorphicDispatcher#compare by not sorting methods

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/.launch/Launch Runtime Eclipse.launch, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
Fixed Broken Launch Config. Resolves #273
=> Fixed Broken Launch Config. Resolves #273

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/compare/CompareFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/compare/CompareFragment2.java
[415677] Language Specific Compare Viewer title (Generator Part)
=> [415677] Language Specific Compare Viewer title

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/source-layout.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/source-layout.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> [Wizard] Include .xtext file in jar created by gradle #284

org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/FlakyFailsFourTimes.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/FlakyFailsTwoTimes.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/IllegalFlakyConfigTest.java
Since now Flaky is also part of .xtext.testing, I copied the tests for
Flaky from .junit4.tests project
=> Added tests for .xtext.testing.Flaky

gradle/eclipse-project-layout.gradle
fixed errors in eclipse (delete test ecores after test)
=> fixed errors in eclipse

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 1.0.0

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/TraceRegionToStringTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/TraceRegionToStringTester.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceRegionMerger.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceRegionSerializer.java
=> [493990] Fixed Duplicate Problem in TraceRegionMerger

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
[410605]  [grammar][terminal] Validate that EOF cannot be inverted
=> [410605]  [grammar][terminal] Validate that EOF cannot be inverted

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/PartialParsingHelperIssue219Test.java, org.eclipse.xtext/src/org/eclipse/xtext/parser/impl/PartialParsingHelper.java
NPE in PartialParsingHelper #219
=> NPE in PartialParsingHelper #219

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java
Signed-off-by: Akos Kitta <kittaakos@gmail.com>
=> GH-323: Re-generated the `UriExtensions`. Fixed whitespaces.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGenerator.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TextFileAccess.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TextFileAccess.java
[481287] Fixed bug in plugin.xml content comparison of xtext generator
=> [481287] Fixed bug in plugin.xml content comparison of xtext generator

org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfo.java
=> Improved error message of Xtext grammar validation

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TracingSugarTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TracingSugarTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/CompositeGeneratorNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeExtensions.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/IGeneratorNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/IndentNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/NewLineNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TemplateNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TextNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TraceNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TracingSugar.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/CompositeGeneratorNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeExtensions.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/IGeneratorNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/IndentNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/NewLineNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TemplateNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TextNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TraceNode.java
* IndentNode indents the first line
* Match TemplateNode to this semantic change
* Code cleanup and comments
=> Improvements of new tracing infrastructure

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/debug/HiddenRegionFormattingToString.java
=> Made Code Guava 21 Compatible

.gitignore, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/splitting/AntlrLexerSplitterTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TemplateNodeTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TracingSugarTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/parsetree/formatter/XtextFormatterTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/SerializerValidationDiagnosticsTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/util/StringsDiffTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TemplateNodeTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TracingSugarTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/SerializerValidationDiagnosticsTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/util/StringsDiffTest.java
Some tests are falling due to windows line separators.
Fix it.
=> Windows tests fix (linesep)

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java
Fixed CliWizardIntegrationTest on windows. #343
=> Fixed CliWizardIntegrationTest on windows. #343

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TracingSugarTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TracingSugarTest.java
Fixed TracingSugarTest on Windows. #343
=> Fixed TracingSugarTest on Windows #343

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
=> better message in parsing test

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Fixed problem with the initial build after project creation in maven tycho
https://github.com/eclipse/xtext-eclipse/issues/272
=> Fixed problem with the initial build after project creation in maven tycho

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/validation/ValidationTestHelper.java
- Introduce enum Mode with the DEFAULT, EXACT, REGEX values.
- Modify the validation issue matching mechanism to consider the current
value of this parameter.
=> [#315] Enable issue matching customization of the ValidationTestHelper.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
updated target platform to oxygen. fixes https://github.com/eclipse/xtext-eclipse/issues/242
=> updated target platform to oxygen.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TypeReference.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TypeReference.java
fix problem with bad naming convention epackages #161 
=> fix problem with bad naming convention epackages

.project, org.eclipse.xtext.ide.tests/.project, org.eclipse.xtext.ide/.project, org.eclipse.xtext.testing/.project, org.eclipse.xtext.testlanguages.ide/.project, org.eclipse.xtext.testlanguages/.project, org.eclipse.xtext.tests/.project, org.eclipse.xtext.util/.project, org.eclipse.xtext.xtext.bootstrap/.project, org.eclipse.xtext.xtext.generator/.project, org.eclipse.xtext.xtext.ide/.project, org.eclipse.xtext.xtext.wizard/.project, org.eclipse.xtext/.project
After importing the projects fresh into workspace Buildship does add the gradleprojectbuilder now
=> gradleprojectbuilder added by Buildship project import

org.eclipse.xtext/src/org/eclipse/xtext/linking/impl/DefaultLinkingService.java
=> [519241] Throw AssertionError when scope provider returns null

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java
=> fix #301: Rollback bc autowrap may ignore change from IAutoWrapFormatter

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/util/InMemoryURIHandler.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/util/InMemoryURIHandler.java
=> Allow to fill the InMemoryURIHandler programmatically with content

org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/LiveShadowedResourceDescriptions.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/ResourceSetBasedResourceDescriptions.java
=> fixed #383: LiveShadowedResourceDescriptions should be live

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/ISequentialRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractEObjectRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractHiddenRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeSemanticRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringSemanticRegion.java
=> Make it easier to traverse text regions of a TextRegionAccess

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/CodeActionTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeLensService.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/validation/TestLanguageValidator.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CodeActionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeLensService.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/TestLanguageValidator.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>
=> [LSP] Added language hook for ‘codeAction’.

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/MultiProjectTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/OpenDocumentTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ServerTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/MultiProjectTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ServerTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>
=> [LSP] Fixed concurrency issues in RequestManager

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/concurrent/RequestManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/RequestManager.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>
=> [lsp testing] switched back to synchronous testing mode.

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeModelBasedRegionAccessBuilder.java
=> [textRegionAccess] Make state of `NodeModelBasedRegionAccessBuilder` accessible in subclasses

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeModelBasedRegionAccessBuilder.java
Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>
=> [textRegionAccess] Fixed missing import.

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/IAstRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/IEObjectRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/ISemanticRegion.java
=> [textRegionAccess] simplified inheritance hierarchy

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java
generate initialization of nameMapping with chunked method calls #419
=> generate initialization of nameMapping with chunked method calls #419

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormattableDocumentTest.java
Fixed FormattableDocumentTest.autoWrapInsert on windows #417
=> Fixed FormattableDocumentTest.autoWrapInsert on windows

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/commands/CommandRegistryTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/commands/CommandRegistryTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/commands/IExecutableCommandService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/commands/IExecutableCommandService.java
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>
=> [lsp] added `workspace/executeCommand` support (fixes #425)

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/serializer/ChangeSerializerTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/serializer/ChangeSerializerTestHelper.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/serializer/ChangeSerializerTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/serializer/ChangeSerializerTestHelper.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectDescriptionDeltaProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/SerializerChangeRecorder.java
=> [ChangeSerializer] use language specific IEObjectDescriptionProvider

org.eclipse.xtext.tests/build.properties, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/IEObjectRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractEObjectRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeModelBasedRegionAccessBuilder.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringBasedTextRegionAccessDiffAppender.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/TextRegionAccessBuildingSequencer.java
=> [TextRegionAccess] keep track of containment among EObjectRegions

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RelatedResourcesProvider.java
=> [ChangeSerializer] bugfix in related resource computation

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectSnapshotProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ReferenceUpdaterContext.java
=> [ChangeSerializer] be more robust regarding broken xrefs

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractRegionAccess.java
=> fixed #438: error in ITextRegionAccess.regionForLineAtOffset(int)

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.java
According to the LSP, `dynamicRegistration` can be undefined in the JSON message.
=> Handle the case that dynamicRegistration is null

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
Don't publish issues with severity ignore #453
=> Don't publish issues with severity ignore #453

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/node/TracingSugarTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/node/TracingSugarTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeExtensions.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TraceNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/Traced.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TracedAccessors.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeExtensions.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TraceNode.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/Traced.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TracedAccessorsProcessor.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TracedProcessor.java
[Tracing] Allow to specify UseForDebugging #467
=> [Tracing] Allow to specify UseForDebugging #467

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/encoding/EncodingTest.java
removed EncodingTest.testSetup #348
=> removed EncodingTest.testSetup #348

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/indentation/AbstractCompletePrefixProviderTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/indentation/AbstractCompletePrefixProviderTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/indentation/IndentationAwareLanguageTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/indentation/NodeModelTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/parser/indentation/IndentationAwareLanguageTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/parser/indentation/NodeModelTest.java
=> fixed indent tests on windows #460

org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/AbstractPortableURIsTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/URIsInEcoreFilesTest.java
=> URIsInEcoreFilesTest fails in Eclipse

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/org.xtext.example.lsGradleApp/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
Changed wizard test expectation
=> [#355] Update MWE to 2.9.1

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> [#355] Update repository URLs

org.eclipse.xtext.ide.tests/model/generated/IndentationAwareUiTestLanguage.ecore, org.eclipse.xtext.ide.tests/model/generated/IndentationAwareUiTestLanguage.genmodel, org.eclipse.xtext.ide.tests/testlang-src-gen/org/eclipse/xtext/ide/tests/testlanguage/indentationAwareUiTestLanguage/impl/IndentationAwareUiTestLanguagePackageImpl.java
=> Regenerated test languages

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectDescriptionProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectSnapshotProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RecordingXtextResourceUpdater.java
=> [ChangeSerilizer] don't NPE on broken ReferenceDescriptions

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ReferenceUpdater.java
=> [ChangeSerializer] fixed potential NPEs

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/RuntimeProjectConfig.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/RuntimeProjectConfig.java, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> set version to 2.14

org.eclipse.xtext.ide.tests/.classpath, org.eclipse.xtext.testlanguages.ide/.classpath
=> [eclipse/xtext#1129] Automatic changes by Buildship

org.eclipse.xtext/src/org/eclipse/xtext/serializer/impl/Serializer.java
Fix for issue #537: Added null guards to all relevant public methods of the Serializer class.
=> Fix for #537: Added null guards

org.eclipse.xtext.xtext.ide/src-gen/org/eclipse/xtext/xtext/ide/AbstractXtextIdeModule.java
I ran `./gradlew generateXtextLanguage` and these changes happend. 😄
=> Regenerated xtext language

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/IFileSystemScanner.xtend, org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/IFileSystemScanner.java, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/UriExtensions.java
correctly decode vs code uris on windows #528
=> correctly decode vs code uris on windows #528

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
=> use newer gradle plugin

org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaVersion.java
=> added support for Java 9 # 500

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java
Fixed Test Problem on Windows #557
=> Fixed Test Problem on Windows #557

org.eclipse.xtext.tests/src/org/eclipse/xtext/naming/DeclarativeQualifiedNameConverterTest.java, org.eclipse.xtext/src/org/eclipse/xtext/naming/IQualifiedNameConverter.java
=> Refactoring & additional tests

org.eclipse.xtext/src/org/eclipse/xtext/validation/ConfigurableIssueCodesProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/IssueCodes.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java
moved 'copy java problems' configurable issue code to xtext core 
https://github.com/eclipse/xtext-core/issues/544
=> moved 'copy java problems' configurable issue code to xtext core 

org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameIssue520Test.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ServerLauncher.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.java
=> regenerated xtend code (java 9 java.lang.Module conflict)

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainerTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainerTest.java
=> GH-568 ... more assertions

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/importHandling/ImportTestHelper.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/PartialContentAssistTestLanguageIdeInjectorProvider.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/TestLanguageIdeInjectorProvider.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/importHandling/ImportTestHelper.java, org.eclipse.xtext.testlanguages.ide/src/org/eclipse/xtext/testlanguages/xtextgrammar/ide/XtextGrammarTestLanguageIdeInjectorProvider.java
=> Fixed broken tests #571

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/SerializableResourceDescription.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/SerializableEObjectDescription.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/SerializationExtensions.java
=> made code of resource storage facade more consistent

org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
=> Fixed a typo in XtextValidator

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[#602] [J9][Wizard] Use latest Oxygen Release in Target
=> [#602] [J9][Wizard] Use latest Oxygen Release in Target

gradle/eclipse-project-layout.gradle
=> [529291] Replace @build@ token in about.mappings

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/JavaVersionTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaVersion.java
=> [#517] Move More Code to JavaVersion

org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/SemanticRegionFinderTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/persistence/PortableURIsTest.java, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/FileSystemAccessQueue.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/URIBasedFileSystemAccess.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/StorageAwareResource.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.java
=> [420984] Compiler optimization: Suppress creation of unused exception var

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
[#611] Fixed broken/outdated javadoc
=> [#611] Fixed broken/outdated javadoc

org.eclipse.xtext/src/org/eclipse/xtext/parser/antlr/AbstractInternalAntlrParser.java, org.eclipse.xtext/src/org/eclipse/xtext/service/AllRulesCache.xtend, org.eclipse.xtext/src/org/eclipse/xtext/service/GrammarProvider.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/service/AllRulesCache.java
[#550] Cache AbstractInternalAntlrParser.createAllRules
=> [#550] Cache AbstractInternalAntlrParser.createAllRules

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[#596] updated tycho version to 1.1.0 to support java 9 in tycho builds as well
=> [#596] updated tycho version to 1.1.0 to support java 9 in tycho builds as well

org.eclipse.xtext.ide.tests/.gitignore, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java
[#636] Removed Test order dependency from UriExtensionsTest
=> [#636] Removed Test order dependency from UriExtensionsTest

org.eclipse.xtext/src/org/eclipse/xtext/mwe/AbstractReader.java
Signed-off-by: René Purrio <rpurrio@itemis.de>
=> Print mwe2 syntax in error message

org.eclipse.xtext/src/org/eclipse/xtext/mwe/Reader.java
=> [doc] Added MWE2 usage example

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/FormattingTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/FormattingTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/formatting/FormattingService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[#638] Use Formatting options passed by the client
=> [#638] Use Formatting options passed by the client

org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/bracketmatching/BracePair.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/AbstractIdeTemplateProposalProvider.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/ContentAssistEntry.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/AlternativeImageDescription.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/DecoratedImageDescription.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/labels/SimpleImageDescription.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/RenameChange.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/ResourceRelocationChange.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerAccess.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/FileInfo.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/logging/LoggingTester.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/LineAndColumn.java, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/GuiceModuleAccess.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TypeReference.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrGrammar.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/CombinedGrammarMarker.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/EPackageInfo.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IncrementalBuilder.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/Indexer.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/OutputConfigurationAdapter.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/AbstractURIWrapper.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/PortableURIs.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/xtext/OriginalElement.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/xtext/OriginalGrammar.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/xtext/RuleWithParameterValues.java
Regenerated against lastest xbase-lib
https://github.com/eclipse/xtext/issues/1174
=> Regenerated against lastest xbase-lib

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/serializer/PartialSerializationTestLanguageReferenceUpdater.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/serializer/PartialSerializationTestLanguageReferenceUpdater.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RelatedXtextResourceUpdater.java
=> [ChangeSerializer] fixed a potential NPE

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/HiddenRegionPartAssociator.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringBasedTextRegionAccessDiffAppender.java
=> [hidden regions] Code Cleanup

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/hooks/IReferenceUpdaterContext.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectDescriptionDeltaProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ReferenceUpdater.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ReferenceUpdaterContext.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RelatedXtextResourceUpdater.java
=> [ChangeSerializer] don't update local refs in related resources

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/XtextResourceSetTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractResourceSetTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractXtextResourceSetTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/NullResource.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/ResourceSetTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/SynchronizedXtextResourceSetTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/XtextResourceSetTest.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java
=> [#476] Support EMF's ResourceLocators in XtextResourceSet.

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/GlobalRegistries.java
=> [522715] Copy/Clear new EAnnotationValidator registry map in EMF 2.14+.

org.eclipse.xtext.util/src/org/eclipse/xtext/util/NonRecursiveEContentAdapter.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/CancelableDiagnostician.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextLinker.java
=> [#449] Avoid stack overflow with deep EMF containment trees.

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/RegionAccessBuilderTest.java
Signed-off-by: Florian Stolte <fstolte@gmx.de>
=> Fixed a test that did not work on windows due to line ending issues

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentHighlightTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/signatureHelp/SignatureHelpServiceImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/commands/ExecutableCommandRegistry.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTestHelper.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/indentation/NodeModelTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/Formatter2Fragment2Test.xtend, org.eclipse.xtext.util/src/org/eclipse/xtext/util/internal/AlternateJdkLoader.xtend, org.eclipse.xtext.xtext.bootstrap/src/org/eclipse/xtext/xtext/bootstrap/XtextLangGeneratorModule.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/SimpleProjectWizardFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/templates/CodetemplatesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorNaming.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/URIBasedFileSystemAccess.xtend, org.eclipse.xtext/src/org/eclipse/xtext/resource/ResourceServiceProviderServiceLoader.xtend, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/ProjectDescriptionBasedContainerManager.xtend, org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/PortableURIs.xtend
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
=> Removed redundant modifiers

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TemplateNode.xtend, org.eclipse.xtext/src/org/eclipse/xtext/resource/DerivedStateAwareResource.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TemplateNode.java
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>
=> Fixed warnings

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
=> use lsp4j 0.4.0-SNAPSHOT as workaround for #705

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext/META-INF/MANIFEST.MF
=> [eclipse/xtext#1190] Narrowed the version range for asm to [6.1.1,6.2.0)

org.eclipse.xtext.util/src/org/eclipse/xtext/util/Files.java
Also refactored methods to use Guava
=> [refactoring] Deprecate methods with correspondence in Guava

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[#714] consume lsp4j 0.4.0 final
=> [#714] consume lsp4j 0.4.0 final

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ServerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ServerTest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/build/IncrementalBuilderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/build/IncrementalBuilderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/build/IncrementalBuilder.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/IncrementalBuilder.java
[#716] [LSP] Problems for a deleted file are shown after deletion
=> [#716] [LSP] Problems for a deleted file are shown after deletion

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
[#724] fixed compile errors with non xbase languages
=> [#724] fixed compile errors with non xbase languages

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
[#664] fixed generation of val prefs/issue codes when deprecation disabled
=> [#664] fixed generation of val prefs/issue codes when deprecation disabled

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/AbstractJUnitIntegrationTest.java
=> removed unused imports

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> use tycho 1.2.0 in the wizard

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/Scope.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
Adds a dependency on org.junit.jupiter:junit-jupiter-engine:5.1.0.
=> [#666] Extended Gradle build for JUnit 5 test execution

Jenkinsfile, gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml, releng/releng-target/xtext-core.target.target
[release] Increment version to 2.15.0
=>  [release] Increment version to 2.15.0

gradle/versions.gradle, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1178]  bootstrap against 2.14
=> [eclipse/xtext#1178]  bootstrap against 2.14

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
Signed-off-by: Arshad <a.adavani@itemis.com>
=> Switched to Tycho 1.2.0 in the wizard project. Fixed test cases.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java
It is not always wanted to have your code be printed out when an error occurs
=> Allow to not print source code in LSP

gradle/p2-deployment.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
=> updated orbit to photon release

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/WizardConfigurationTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/WizardConfigurationTest.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/SourceFolderDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/SourceLayout.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestedProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/P2RepositoryProject.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/SdkFeatureProject.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/SourceFolderDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestedProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.java
- Support output folders per source fodler
- Support test source folder
=> [eclipse/xtext-eclipse#677] Additional source folder support.

gradle/p2-deployment.gradle, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1168] set minimal target to oxygen
=> [eclipse/xtext#1168] set minimal target to oxygen

org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/GenericFormatter.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/idea/parser/antlr/PsiAntlrGrammarGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarWithActionsGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrGrammarGenerator.java
=> regenerated against latest xtend

org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java
[#790] Search Check annotation only once
=> [#790] Search Check annotation only once

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/formatting/FormattingService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
=> fixed broken javadoc

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/concurrent/RequestManagerTest.java
=> [#622] set flaky testcase to ignore

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/KeywordHelperTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/KeywordHelperTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/KeywordHelper.java
[#804] Added EOF to keyword escape list
=> [#804] Added EOF to keyword escape list

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RecordingXtextResourceUpdater.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/RelatedXtextResourceUpdater.java
=> [ChangeSerializer] Don't record derived state

org.eclipse.xtext/src/org/eclipse/xtext/findReferences/TargetURIConverter.java
Will also make the UI one override from this one
=> Added TargetURIConverter to non UI

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/antlr/ContentAssistContextFactory.java
If the lexer returns multiple invalid tokens in succession only the last
one is taken into account for content assist. Especially if there are
keywords only (no ID or similar) this is an issue because only the last
character is used as prefix.
The fix assumes that ALL tokens with syntax errors that come in
succession are relevant for content assist. It seems not to be useful to
execute content assist otherwise.
This can never be reproduced with any grammar that includes standart
"Terminals" because of the ID and the ANY_OTHER rule. The ID rule makes
sure that the start is usually read as only ONE token, whereas the
ANY_OTHER rule ensures there is never a lexer error.
As this is merely a side case for grammars without an ID it seems to much overhead to define an extra test language to …
=> [#69] Fix content assist if lexer returns multiple invalid tokens.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext-core#822] use 2018-09 in target platform
=> [eclipse/xtext-core#822] use 2018-09 in target platform

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.xtend, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/src/main/java/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/org.xtext.example.lsGradleApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/src/main/java/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
=> ConfigurableIssueCodesProvider generated #825

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePluginP2/org.xtext.example.eclipsePluginP2/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle/src/main/java/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/org.xtext.example.lsGradleApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenApp/org.xtext.example.lsMavenApp.parent/org.xtext.example.lsMavenApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenFatjar/org.xtext.example.lsMavenFatjar.parent/org.xtext.example.lsMavenFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven/src/main/java/org/xtext/example/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
=> Fixing typo: 'corresponsing' -> 'corresponding'

org.eclipse.xtext.tests/src/org/eclipse/xtext/GenerateAllTestLanguages.mwe2
[#834] Fixed GenerateTestLanguages
=> [#834] Fixed GenerateTestLanguages

org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.xtend, org.eclipse.xtext/src/org/eclipse/xtext/tasks/TaskTag.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParser.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/TaskTags.java
=> [eclipse/xtext-eclipse#809] Cache task marker pattern for performance

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#1266] Update to ASM 6.2
=> [eclipse/xtext#1266] Update to ASM 6.2

org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskFinder.xtend, org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.xtend, org.eclipse.xtext/src/org/eclipse/xtext/tasks/TaskTag.xtend, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskFinder.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParser.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/TaskTags.java
=> [#845] Avoid creation of collections if not necessary.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.java
=> [#851] Add xtext builder to example project template.

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[#793] update to lsp4j 0.5.0 final
=> [#793] update to lsp4j 0.5.0 final

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/coloring/ColoringServiceImpl.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/coloring/ColoringServiceImpl.java
=> Mark ColoringServiceImpl as Dreprecated

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> updated versions to 2.16.0

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
restored old state for MergableManifest
=> restored old state for MergableManifest

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/StringsTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java
Cherry-picked change from https://github.com/eclipse/xtext-core/pull/870 for master
=> Removed copied code from Strings.java

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/CompletionTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UnknownProjectConfigTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageProposalCreator.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CompletionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UnknownProjectConfigTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageProposalCreator.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalProvider.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalProvider.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>
=> Handle ContentAssistEntry.getTextReplacements in ContentAssistService

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/JavaVersionTest.java
=> Testing more methods from JavaVersion

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>
=> Make it possible to test position based CodeActions

org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/SimpleAttributeResolverTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/SimpleAttributeResolver.java
=> [539677] getValue should return null for null arg

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> updated to orbit 2018-12-M1

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[eclipse/xtext#1280] updated version of shadow jar plugin
=> [eclipse/xtext#1280] updated version of shadow jar plugin

releng/pom.xml
Added property ‚upstreamBranch‘ which is considered by adjustPipelines.sh script
=> [eclipse/xtext-umbrella#65] Adjust upstream branch

org.eclipse.xtext.util/src/org/eclipse/xtext/util/Exceptions.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/PolymorphicDispatcher.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/SimpleCache.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java, org.eclipse.xtext/src/org/eclipse/xtext/parsetree/reconstr/ITransientValueService.java
=> fixed javadoc

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerShutdownAndExitHandler.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
=> [#885] make LSP server exit behaviour configurable

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
=> #918: Fix MergeableManifest2 and add missing unit tests

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext-core#903] build against 2018-12 in wizard
=> [eclipse/xtext-core#903] build against 2018-12 in wizard

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
=> Updated xtext-gradle-plugin to 2.0.2

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceAsPrimarySourceInstaller.java
[eclipse/xtext#1325] switch to ASM 7
=> [eclipse/xtext#1325] switch to ASM 7

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#1318] fixed broken mvn clean plugin configuration
=> [eclipse/xtext#1318] fixed broken mvn clean plugin configuration

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
[eclipse/xtext#1182] fixed tests with java 11 agains java 8 target
=> [eclipse/xtext#1182] fixed tests with java 11 agains java 8 target

org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/lazy/Bug281990Test.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/lazy/Bug443705Test.java, org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java
=> Performance Fix Cyclic Link Detection

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[#893] build against LSP4J 0.6.0-SNAPSHOT (to catch breaking stuff early)
switch to release is handled in a separate pr
=> [#893] build against LSP4J 0.6.0-SNAPSHOT

gradle/versions.gradle, releng/pom.xml
[#893] build agains lsp4j snapshots
=> [#893] build agains lsp4j snapshots

org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
=> [#959] hasAnnotation: Add null guard

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/CompletionTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeContentProposalProvider.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CompletionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeContentProposalProvider.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalCreator.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalCreator.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java
[eclipse/xtext-core#625] set Item.InsertTextFormat to snippet for snippets
=> [eclipse/xtext-core#625] set Item.InsertTextFormat to snippet for snippets

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[#893] switch to lsp4j 0.6.0 final
=> [#893] switch to lsp4j 0.6.0 final

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> switched to tycho 1.3 in wizard

releng/p2/pom.xml, releng/pom.xml
[eclipse/xtext#1322] switched to tycho 1.3.0
=> [eclipse/xtext#1322] switched to tycho 1.3.0

org.eclipse.xtext.xtext.wizard/build.gradle
=> made args4j non optional

org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java
[#971] make junit5 support api
=> [#971] make junit5 support api

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1372] Use 2019-03 in target platforms
=> [eclipse/xtext#1372] Use 2019-03 in target platforms

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliProjectsCreator.java
=> fixed guava deprecations

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1283] update to MWE 2.10 M2
=> [eclipse/xtext#1283] update to MWE 2.10 M2

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/RepeatedTest.java, releng/pom.xml
Can be used to run tests in a loop for n times
=> Added RepeatedTest annotation to xtext.testing

org.eclipse.xtext/src/org/eclipse/xtext/validation/CompositeEValidator.java
Make creation of exception based diagnostics customizable
=> [#983] Make issue message customizable

org.eclipse.xtext.util/META-INF/MANIFEST.MF
[eclipse/xtext#1391] pin guava version to 21
=> [eclipse/xtext#1391] pin guava version to 21

releng/pom.xml
=> Set sourceEncoding ISO-8859-1

org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/DeclarativeValidatorTest.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java
=> [#985] Make swallowing of NPEs in validation code configurable

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/RepeatedTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/FileSystemAccessQueue.xtend, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.xtend, org.eclipse.xtext/src/org/eclipse/xtext/serializer/acceptor/SequenceFeeder.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/diagnostic/ISemanticSequencerDiagnosticProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/diagnostic/ISyntacticSequencerDiagnosticProvider.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/FileSystemAccessQueue.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/GeneratorNodeProcessor.java
=> fixed some javadocs

org.eclipse.xtext.tests/src/org/eclipse/xtext/EcoreUtil2Test.java, org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java
Added covering test case
makeInvalid moved below single method that uses it & made private
=> isAssignableFrom: check both args for null & identity

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
do not merge before MWE 2.10 is released
=> [eclipse/xtext#1283] switched to MWE 2.10 in wizard

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ValidationIssue1034Test.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ValidationIssue1034Test.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Signed-off-by: Eva Poell <epoell@itemis.com>
=> [#1034] Added Validation that entry rule is not a fragment

org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java
[Issue 1029](https://github.com/eclipse/xtext-core/issues/1029)
Replaced ThreadLocal state.set(null) with state.remove(). And tried to decrement the calls of state.get() by keeping it in a variable if possible.
Might need a closer look, if this works. And sorry for the wrong number (1021 instead of 1029) in the commit! I got mixed up.
Signed-off-by: Eva Poell <epoell@itemis.com>
=> Solve Issue 1029

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[#1054] fixed broken target platform for junit 5
=> [#1054] fixed broken target platform for junit 5

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
[#1053] Wizard: Bump Xtext-Gradle-Plugin to latest (2.0.4)
=> [#1053] Wizard: Bump Xtext-Gradle-Plugin to latest (2.0.4)

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
[eclipse/xtext#1414] prepared master for version 2.18.0
=> [eclipse/xtext#1414] prepared master for version 2.18.0

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> use orbit 2019-06

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/AbstractTestLangLanguageServerTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/FormattingTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/AbstractTestLangLanguageServerTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/FormattingTest.java
=> marked abstract classes as abstract

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ColoringTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ColoringTest.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
=> GH-1074: Exposed the language client class for the LS tests.

org.eclipse.xtext/src/org/eclipse/xtext/validation/CompositeEValidator.java
added missing getter/setter for operationCanceledManager
=> added missing getter/setter for operationCanceledManager

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> [#1077] update to gson 2.8.2

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1412] build against 2019-06 in wizard
=> [eclipse/xtext#1412] build against 2019-06 in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.ui.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
=> PR: Incorrect handling of tycho.testArgLine in the generated POMs

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend
=> harmonized ws

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/ChangeConverter2.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/ChangeConverter2.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/IRenameService2.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService2.java
Well, as the title suggests, there was another race condition in rename.
=> [ls] fixing yet another race in rename

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLanguageIdeModule.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService2.java
=> #923 provide live resource sets to code action service

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> use https in target

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
=> fixed bad comment in test plugin

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
Signed-off-by: Holger Schill <Holger.Schill@itemis.de>
=> Remove implicit IDEA support since it got dropped

1-gradle-build.sh, 2-maven-build.sh, CBI.Jenkinsfile, releng/pom.xml
- externalized build steps into shell scripts for convenient local usage
- added Slack notifications
- configure Maven default goal
=> [eclipse/xtext#1309] Provide Jenkinsfile for Eclipse CBI

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
=> [eclipse/xtext-extras#406] Fix missing newline, add test.

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java
Use a SubMonitor in applyModifications & endRecordChanges to report fine
grained progress. Further this does not rely on knowledge of the number
of passed ticks from the surrounding monitor.
=> [eclipse/xtext#1403] Improve progress monitor utilization

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.tests/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java, releng/pom.xml
[eclipse/xtext#1422] update to tycho 1.4.0
=> [eclipse/xtext#1422] update to tycho 1.4.0

org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
=> [testlanguages] removed superfluous entry in 'Export-Package'

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
=> [lsp] always re-process URIs from cancelled builds

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ProjectManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
- make it easier to extend `ProjectManager`
- mark another unused method
=> [lsp] expose some more API

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/BuildManager.java
=> [lsp] don't swallow partial results from canceled builds

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/NodeModelBuilder.java
More efficient method to intern the array of grammar elements during the building of the node model.
In my benchmarks parsing performance improves between 15% and 20%, the overhead of the interning becomes negligible and GC pressure is reduced (<10%).
Signed-off-by: Lieven Lemiengre lieven.lemiengre@sigasi.com
=> Performance improvement of array interning in NodeModelBuilder

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java
related to https://github.com/eclipse/xtext-eclipse/issues/1053
this PR improves the progress reporting in `ChangeSerializer`.
The current implementation didn't distinguish the iterations in the second loop of `applyModifications(...)`, which cause the most workload.
Besides, cancelation should be definitively checked there!
I removed the reporting from the first loop, since that simply traverses a list and add elements to another list.
I furthermore improved the progress reporting in `endRecordChanges`.
=> [refactoring] improved progress reporting in `ChangeSerializer`

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/ChangeSerializer.java
A follow-up on #1130, replacing the calls of `SubMonitor.beginTask(...)` by `SubMonitor.convert(...)` while keeping my desired reporting behaviour.
=> [refactoring] a bit of progress monitor rework in `ChangeSerializer`

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
=> [eclipse/xtext#1440] Update to ASM 7.1.0.

2-maven-build.sh
[eclipse/xtext#1427] disable p2 mirrors
=> [eclipse/xtext#1427] disable p2 mirrors

gradle/versions.gradle, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/concurrent/WriteRequest.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService2.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/regionaccess/internal/SemanticRegionFinderTest.java, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/GrammarPDAProviderTest.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/GuiceModuleAccess.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrGrammarGenerator.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ecore2xtext/Ecore2XtextExtensions.java
[eclipse/xtext#1437] Bootstrap against 2.18.0.M2
=> [eclipse/xtext#1437] Bootstrap against 2.18.0.M2

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
=> update to gradle 5.4.1

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/internal/InjectorProviders.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/AbstractXtextTests.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidationTestHelper.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java
fixed deprecations with java 11
=> fixed deprecations with java 11

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
=> [eclipse/xtext-core#1082] update to lsp4j 0.7.1

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/RenameContext.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerAccess.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/refactoring/RenameContext.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ILanguageServerAccess.java
=> fixed more warnings

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/WrappingInjectorProvider.java
[#1149] Apply proper restore logic also to SmokeTest infra
=> [#1149] Apply proper restore logic also to SmokeTest infra

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/SocketServerLauncher.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/SocketServerLauncher.java
For debugging, it is often useful to start LSs behind a socket server. This class allows for it.
=> [lsp] added a server socket launcher

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
=> update to lsp4j 0.7.2

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java
=> [lsp] fixed Document.applyEdit for multiple textEdits

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> [eclipse/xtext#1474] Prepare Master for 2.19

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1475] build against orbit 2019-09
=> [eclipse/xtext#1475] build against orbit 2019-09

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
=> [eclipse/xtext#1485] update to mwe 2.11

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/XtextSerializationTokensTest.java
=> fixed some warnings

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> [eclipse/xtext#1490] Bump xtext-gradle-plugin to 2.0.5

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.xtend, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.java
[eclipse/xtext-xtend#818] Adjusted new project wizard
=> [eclipse/xtext-xtend#818] Adjusted new project wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> [eclipse/xtext1475][Wizard] use 2019-09 in target platform

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/Issue1161Test.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/Issue1161Test.java
=> fixed encoding issues

gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew.bat, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew.bat, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew.bat, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew.bat, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew.bat
[eclipse/xtext#1489] update to gradle wrapper 5.5
=> [eclipse/xtext#1489] update to gradle wrapper 5.5

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
=> updated xtext gradle plugin to version 2.0.7

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/org.xtext.example.lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
=> bumped shadow gradle plugin

org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ColoringTest.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
=> regenerate with latest xtend

org.eclipse.xtext.util/META-INF/MANIFEST.MF
=> fixed missing xtext.xtext.ui from xfriends

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> update to jquery 3.4.1

gradle/upstream-repositories.gradle, releng/pom.xml
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> [eclipse/xtext#1507] Adjust lsp4j upstream URL / Use env.JENKINS_URL

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/antlr/internal/Lexer.java
- Avoid infinite loop (editor freeze) on FailedPredicateException.
=> [https://github.com/eclipse/xtext-eclipse/issues/678]

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ValidatorTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/validation/TestLanguageValidator.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ValidatorTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/validation/TestLanguageValidator.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/LanguageServerImpl.java
[#922] Calculate correct position (end) for issues
=> [#922] Calculate correct position (end) for issues

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/UriExtensions.java
[#1163] fixed broken uri encoding when converting to emf uri
=> [#1163] fixed broken uri encoding when converting to emf uri

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1530] adapted wizard to new junit 5 version in orbit
=> [eclipse/xtext#1530] adapted wizard to new junit 5 version in orbit

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> adjusted to timestamp changes in orbit

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Set version to 2.20.0

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/PartialSerializationTestLanguageStandaloneSetup.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/PartialSerializationTestLanguageStandaloneSetup.java
make sure WithTransient Package is always registered
=> make sure WithTransient Package is always registered

gradle/wrapper/gradle-wrapper.properties, gradlew, org.eclipse.xtext.ide.tests/.classpath, org.eclipse.xtext.testing/.classpath, org.eclipse.xtext.tests/.classpath, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/gradlew, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/gradlew, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradlew
[eclipse/xtext#1520] update to gradle 5.6.1
=> [eclipse/xtext#1520] update to gradle 5.6.1

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1538] use orbit 2019-12
=> [eclipse/xtext#1538] use orbit 2019-12

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/MergeableManifest2Test.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest2.java
Remove superflues cancelation of creation process in case of missing
version.
=> #1120 Fix merger in case of line breaks inside identifiers.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.java
=> [https://github.com/eclipse/xtext/issues/1556]

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleApp/org.xtext.example.lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsGradleFatjar/org.xtext.example.lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java
=> use xtext-gradle-plugin 2.0.8

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, releng/pom.xml
[eclipse/xtext#1553] update to tycho 1.5.0
=> [eclipse/xtext#1553] update to tycho 1.5.0

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#1567] Upgrade to asm 7.2
=> [eclipse/xtext#1567] Upgrade to asm 7.2

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, releng/pom.xml
[eclipse/xtext#1566] update to tycho 1.5.1
=> [eclipse/xtext#1566] update to tycho 1.5.1

.gitpod.yml
An initial gitpod config. Pre-builds should be enabled.
=> [gitpod] added basic .gitpod.yml

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
updated jetty to latest release
=> updated jetty to latest release

org.eclipse.xtext.tests/META-INF/MANIFEST.MF
=> removed dep to old generator

org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/SocketServerLauncher.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.java
regenerated with latest xbase.lib
=> regenerated with latest xbase.lib

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/GenerateTestLanguage.mwe2
fixed broken config of formatter fragment
=> fixed broken config of formatter fragment

gradle/manifest-gen.gradle, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#1504] added Eclipse-SourceReferences to manifests
=> [eclipse/xtext#1504] added Eclipse-SourceReferences to manifests

org.eclipse.xtext.ide.tests/build.properties, org.eclipse.xtext.ide.tests/plugin.properties, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/build.properties, org.eclipse.xtext.ide/plugin.properties, org.eclipse.xtext.testing/build.properties, org.eclipse.xtext.testlanguages.ide/build.properties, org.eclipse.xtext.testlanguages/build.properties, org.eclipse.xtext.tests/build.properties, org.eclipse.xtext.util/build.properties, org.eclipse.xtext.xtext.generator/build.properties, org.eclipse.xtext.xtext.ide/build.properties, org.eclipse.xtext.xtext.wizard/build.properties, org.eclipse.xtext/.cvsignore, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/build.properties, org.eclipse.xtext/plugin.properties
[eclipse/xtext#1573] Provide proper build.properties
=> [eclipse/xtext#1573] Provide proper build.properties

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.java
Xtext New Project Wizard / New File Wizard Fragment: add possibilities
to generate toolbar buttons.
=> [https://github.com/eclipse/xtext-eclipse/issues/1229]

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1609] update to mwe 2.11.1
=> [eclipse/xtext#1609] update to mwe 2.11.1

org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/xtextgrammar/XtextGrammarTestLanguage.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/GenerateAllTestLanguages.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/GenerateFormatterTestLanguages.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/GenerateLinkingTestLanguages.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/fragments/GenerateFragmentTestLanguages.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/indentation/GenerateIndentationTestLanguages.mwe2, org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/parameters/GenerateParametersTestLanguages.mwe2
=> fixed deprecations

org.eclipse.xtext.testlanguages/build.properties, org.eclipse.xtext.tests/generator/src/org/eclipse/xtext/tests/TestsEMFGeneratorFragment.xtend, org.eclipse.xtext.tests/generator/xtend-gen/org/eclipse/xtext/tests/TestsEMFGeneratorFragment.java
=> fix unwanted build properties changes

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
=> updated to lsp4j 0.8.1

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.21.0

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
[#1312] fixed broken stub code
=> [#1312] fixed broken stub code

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/BinaryFileAccess.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/BinaryFileAccess.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/fileWizard/TemplateFileWizardFragment.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/projectWizard/TemplateProjectWizardFragment.java
=> [#1321] Do not override icons when regenerate.

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/DocumentTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/Document.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/Document.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
=> [#1108] Update the year in the copyright headers.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
use 2020-03 in target platform
=> use 2020-03 in target platform

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1605] update orbit to 2020-03
=> [eclipse/xtext#1605] update orbit to 2020-03

org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parsetree/reconstr/serializer/SerializationErrorTestLanguageSemanticSequencer.java
=> regenerated test langs

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/ITextRegionDiffBuilder.java
=> [#1343] Fix invalid link in javadoc.

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ColoringTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/TestLanguageRuntimeModule.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ColoringTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/TestLanguageRuntimeModule.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
Enhance Dreprecations (get fewer warnings)
=> Enhance Dreprecations (get fewer warnings)

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
[#1351] match milestone versions in test too
=> [#1351] match milestone versions in test too

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, releng/pom.xml
[eclipse/xtext#1643] update to tycho 1.6.0
=> [eclipse/xtext#1643] update to tycho 1.6.0

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
=> Remove trailing whitespace from EMFGeneratorFragment2 (plugin.xml).

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ImplicitFragment.java
=> Use consistent indentation in the ImplicitFragment (plugin.xml).

org.eclipse.xtext.tests/src/org/eclipse/xtext/nodemodel/AbstractNodeTest.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/INode.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/AbstractNode.java
=> [#1303] Throw exception instead of returning null.

releng/releng-target/xtext-core.target.target
=> use junit 4.12 explicitely

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/signatureHelp/SignatureHelpServiceImpl.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/signatureHelp/SignatureHelpServiceImpl.java, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/signatureHelp/ISignatureHelpService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
=> [#1244] lsp4j 0.9.0

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/HoverTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/CompletionTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/HoverTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/hover/HoverService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/hover/IHoverService.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/hover/HoverContext.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/hover/HoverService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/hover/IHoverService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[#1372] update hover service to use MarkupContent
=> [#1372] update hover service to use MarkupContent

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
[#1386] fixed wizard formatter config for new xtext project for existing ecore model
=> [#1386] fixed wizard formatter config for new xtext project for existing ecore model

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
I added the suggested line into the IdeProjectDescriptor and updated the two tests using the wizards.
The gradle and maven build are working.
=> Hn issue1382

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[#1384] removed xpand/generator(1) dependency from wizard for existing ecore models
=> [#1384] removed xpand/generator(1) dependency from wizard for existing ecore models

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
=> test with MWE 2.11.2.M3

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1641] update to junit 5.6
=> [eclipse/xtext#1641] update to junit 5.6

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/WorkspaceFoldersTest.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/WorkspaceFoldersTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/IMultiRootWorkspaceConfigFactory.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/MultiRootWorkspaceConfigFactory.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ProjectManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ServerModule.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/ServerModule.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
=> [LS] support multiple workspace root folders

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/BuildManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/coloring/IColoringService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/formatting/FormattingService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/occurrences/IDocumentHighlightService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/ChangeConverter.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService.xtend, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/UriExtensions.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/codeActions/ICodeActionService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/formatting/FormattingService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/ChangeConverter.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService.java, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService2.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[#1394] marked more elements to be removed in 2.22
@JanKoehnlein please check if i missed to mark something
=> [#1394] marked more elements to be removed in 2.22

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1673] udpate to MWE 2.11.2
=> [eclipse/xtext#1673] udpate to MWE 2.11.2

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
Signed-off-by: Ryan Dunn <dunnry@hotmail.com>
Fixes #1381 and #1380
=> Adding ResourceOperation toExpectation and fixing NPE on WorkspaceEdit

org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/AssertableDiagnostics.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTester.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ExternalDependency.java
=> fixed unused imports

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ValidatorTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/ValidatorTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[#1244] adapted to changes in Diagnostic.code in LSP4j
=> [#1244] adapted to changes in Diagnostic.code in LSP4j

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.22.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/bracketmatching/XtextBracePairProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/ILanguageServerExtension.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/Traced.java, org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/node/TracedAccessors.java
regenerated xtend code & cleanup imports
=> regenerated xtend code & cleanup imports

org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/AbstractFile.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/BinaryFile.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/PlainTextFile.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectsCreator.java, org.eclipse.xtext/src/org/eclipse/xtext/parser/antlr/AbstractIndentationTokenSource.java, org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/DelegatingScopeProvider.java
=> fixed more unused imports

org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/internal/EmfAdaptable.java, org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/internal/Log.java
=> regen xtend code

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1685] use 2020-06 update site
=> [eclipse/xtext#1685] use 2020-06 update site

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1682] update orbit to 2020-06
=> [eclipse/xtext#1682] update orbit to 2020-06

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, releng/pom.xml
=> [https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceAsPrimarySourceInstaller.java
[eclipse/xtext#1649] update to ASM 8.0
=> [eclipse/xtext#1649] update to ASM 8.0

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/WrappingInjectorProvider.java
made wrapping injector provider guice 4 ready
=> made wrapping injector provider guice 4 ready

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1765] update to MWE 2.11.3.M3
=> [eclipse/xtext#1765] update to MWE 2.11.3.M3

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/LineSeparatorHarmonizerTest.java
=> Fix typo in LineSeparatorHarminizerTest test class name.

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest3.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest3.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.xtend, org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService2.java
=> [lsp] properly rename quoted identifiers

org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/server/rename/RenameService2.java
=> added missing generated code

org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelperTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/NamesAreUniqueValidatorTest.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/DefaultResourceDescriptionManager.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/IsAffectedExtension.java, org.eclipse.xtext/src/org/eclipse/xtext/service/DefaultRuntimeModule.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/AbstractDeclarativeValidator.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/DefaultUniqueNameContext.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/INamesAreUniqueValidationHelper.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/LocalUniqueNameContext.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidator.java, org.eclipse.xtext/src/org/eclipse/xtext/validation/UniqueInResourceContext.java
=> [#1466] Global unique name validator

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/XtextProjectConfig.java
=> #[1427] Update last modified year to 2020 in the Copyright headers.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.java
=> Formatting XbaseGeneratorFragment2.xtend file.

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1770] update to mwe 2.11.3 final
=> [eclipse/xtext#1770] update to mwe 2.11.3 final

org.eclipse.xtext/src-gen/org/eclipse/xtext/common/services/TerminalsGrammarAccess.java, org.eclipse.xtext/src-gen/org/eclipse/xtext/services/XtextGrammarAccess.java
=> [#269] Regenerate Xtext Language via the GenerateXtext.mwe2 workflow.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/outline/QuickOutlineFragment2.xtend, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/refactoring/RefactorElementNameFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/outline/QuickOutlineFragment2.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/refactoring/RefactorElementNameFragment2.java
=> Formatting QuickOutlineFragment2 and RefactorElementNameFragment2 files.

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.23.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java
=> [lsp] avoid negative positions

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
=> [https://github.com/eclipse/xtext-web/issues/240] Use correct param key.

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java
[#1524] made InjectionExtension compatible with older junit5 versions again
=> [#1524] made InjectionExtension compatible with older junit5 versions again

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1781] update orbit to 2020-09
=> [eclipse/xtext#1781] update orbit to 2020-09

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in wizard
=> [eclipse/xtext#1784] use download.eclipse.org/releases/2020-09 in wizard

org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/project/RuntimeProjectConfig.java
=> regenerated with latest aa

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/OnChangeEvictingCacheAdapterTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java
=> [#1497] Don't clear the cache on bulk changes to errors or warnings

org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java
=> [#1497] Remove unused import

org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java
=> [#1536] Make LazyLinkingResource#proxyInformation available to sub-types

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java
=> [ls] copy build listener list before notification

org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextLinkingDiagnosticMessageProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
Signed-off-by: nbhusare <neerajbhusare@gmail.com>
=> Add new Xtext editor quickfixes on *.xtext files

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/InternalNodeModelUtils.java
An exception without any message is not all that useful
=> Add message to IndexOutOfBoundsException in InternalNodeModelUtils

releng/releng-target/xtext-core.target.target
[eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0
=> [eclipse/xtext#1816] harmonize includeSource to true in preparation for tycho 2.0

org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TracedAccessorsProcessor.java
predictable sorting in TracedAccessors
=> predictable sorting in TracedAccessors

org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/parsetree/reconstr/serializer/SerializationErrorTestLanguageSemanticSequencer.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/multiinheritancetest.ecore, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfo.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfoAccess.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/EClassifierInfos.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/ElementTypeCalculator.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreInterpretationContext.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformer.java
=> Improved validation against imported ecore meta model

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java
made ContentAssistFragment2 better customizable
=> made ContentAssistFragment2 better customizable

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.24.0

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/PolymorphicDispatcherTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/valueconverter/INTValueConverterTest.java
fixed warnings when compiling against Java 11
=> fixed warnings when compiling against Java 11

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/InternalNodeModelUtils.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java
=> [#1568] Add restricted API to allow access to internals of the node model

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1828] update orbit to 2020-12
=> [eclipse/xtext#1828] update orbit to 2020-12

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12
=> [eclipse/xtext#1831] update to download.eclipse.org/releases/2020-12

org.eclipse.xtext/src/org/eclipse/xtext/xtext/OverriddenValueInspector.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/PredicateUsesUnorderedGroupInspector.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextRuleInspector.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextScopeProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
=> Improve performance of Xtext editor with large grammars

releng/pom.xml
=> use dev bom in tycho build

org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/EObjectAtOffsetTest.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/EObjectAtOffsetHelper.java
=> [#1521] Return root on parse success and no other element found.

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/TraceRegionSerializerTest.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/URIBasedFileSystemAccess.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/internal/AbstractTrace.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
[eclipse/xtext#1850] Fix resource leaks
=> [eclipse/xtext#1850] Fix resource leaks

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/AbstractJUnitIntegrationTest.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/XtextRunnerTest.java, org.eclipse.xtext.testing/tests/org/eclipse/xtext/testing/tests/junit5/InjectionExtensionTest.java
=> [eclipse/xtext#1851] More tests for the tests

org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/CompositeValidatorWithEObjectValidatorTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/CompositeValidatorWithoutEObjectValidatorTest.java
made tests order independent. fixes #1582
=> made tests order independent. fixes #1582

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoApp/org.xtext.example.lsMavenTychoApp.parent/org.xtext.example.lsMavenTychoApp.target/org.xtext.example.lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.lsMavenTychoFatjar/org.xtext.example.lsMavenTychoFatjar.parent/org.xtext.example.lsMavenTychoFatjar.target/org.xtext.example.lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.target/org.xtext.example.mavenTychoJ9.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/TraceAsPrimarySourceInstaller.java
[eclipse/xtext#1852] Update to ASM 9
=> [eclipse/xtext#1852] Update to ASM 9

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
[eclipse/xtext-web#262] update to jquery 3.5.1
=> [eclipse/xtext-web#262] update to jquery 3.5.1

org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoJ9/org.xtext.example.mavenTychoJ9.parent/org.xtext.example.mavenTychoJ9.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> update to latest jetty

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ecore/EMFGeneratorFragment2.java
=> fixed javadoc error (Java 11)

org.eclipse.xtext.tests/src/org/eclipse/xtext/documentation/impl/MultiLineCommentDocumentationProviderTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/tasks/DefaultTaskFinderTest.xtend, org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskFinderTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringBasedTextRegionAccessDiffAppender.java
=> fixed some bugs

org.eclipse.xtext.tests/src/org/eclipse/xtext/tests/TemporaryFolder.java
=> fix temp folder security flaw

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11/src/mydsl/GenerateMyDsl.mwe2, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
[eclipse/xtext#1855] update to junit 5.7
=> [eclipse/xtext#1855] update to junit 5.7

org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/TestLangLSPExtension.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/ide/server/CodeActionService.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/ServerRefactoringIssueAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.java, org.eclipse.xtext.testlanguages.ide/src/org/eclipse/xtext/testlanguages/fileAware/ide/refactoring/FileAwareTestLanguageReferenceUpdater.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/AntlrGrammarComparator.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/SynchronizedXtextResourceSetTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainerTest.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/cli/CliWizardIntegrationTest.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TypeReference.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/LanguageDescriptor.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegionToString.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TemplateNode.java, org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/node/TracedAccessorsProcessor.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/LiveShadowedChunkedContainer.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/impl/ChunkedResourceDescriptions.java, org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/SerializableResourceDescription.java, org.eclipse.xtext/src/org/eclipse/xtext/tasks/PreferenceTaskTagProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/FlattenedGrammarAccess.java
=> cleanup x2j

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
avoid classloading issues with osgi bundle
=> avoid classloading issues with osgi bundle

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2
=> [eclipse/xtext#1866] update to MWE(2) 1.6.0/2.12.0 M2

org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> ease mwe version update

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensions2Test.java
=> fixed test on win

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/contentassist/ContentAssistContextFactoryTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/contentassist/ContentAssistContextTestHelper.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/editor/contentassist/PartialContentAssistTestLanguageContextFactoryTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/indentation/AbstractCompletePrefixProviderTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/indentation/IndentationAwareCompletionPrefixProviderTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/PrepareRenameTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest2.xtend, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenameTest3.xtend, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/editor/contentassist/ContentAssistContextFactoryTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/editor/contentassist/ContentAssistContextTestHelper.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/editor/contentassist/PartialContentAssistTestLanguageContextFactoryTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/indentation/AbstractCompletePrefixProviderTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/indentation/IndentationAwareCompletionPrefixProviderTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/PrepareRenameTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest2.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/RenameTest3.java
cleaner exception handling in tests
=> cleaner exception handling in tests

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/commands/CommandRegistryTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SemanticHighlightingTest.xtend, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/TestLanguageRuntimeModule.java, org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/editor/syntaxcoloring/SemanticHighlightingStyleToTokenMapper.java, org.eclipse.xtext.ide.tests/xtend-gen/org/eclipse/xtext/ide/tests/server/SemanticHighlightingTest.java, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/ISemanticHighlightingStyleToTokenMapper.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semanticHighlight/SemanticHighlightingRegistry.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[eclipse/xtext-core#1566] update to LSP4J 0.10.0
=> [eclipse/xtext-core#1566] update to LSP4J 0.10.0

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
security fix for jetty in wizard
=> security fix for jetty in wizard

org.eclipse.xtext.testing/META-INF/MANIFEST.MF
export all packages as internal
=> export all packages as internal

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/PortableURIs.java
=> fixed typos

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
=> [releng] Update MWE to 1.6.0/2.12.0

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/JavaFormatterGrammarTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextFormatterJava.java
=> [#1489] Several formatter fixes.

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
generate serialVersionUID for Java Servlet
=> generate serialVersionUID for Java Servlet

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/JavaFormatterGrammarTest.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextFormatterJava.java
=> [#1625] Added a lot of tests and a few fixes to the formatter.

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.25.0

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SignatureHelpTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/refactoring/IRenameStrategy2.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Files.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.java, org.eclipse.xtext/src/org/eclipse/xtext/findReferences/TargetURIs.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/ITextRegionDiffBuilder.java, org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java, org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/MapBasedScope.java, org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/MultimapBasedScope.java
Signed-off-by: miklossy <miklossy@itemis.de>
=> Fixing typos in the javadoc comments.

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1882][2021-03] Update Orbit
DO NOT merge yet
=> [eclipse/xtext#1882][2021-03] Update Orbit

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
generate serialVersionUID for Xtend based Xtext Servlet too
=> generate serialVersionUID for Xtend based Xtext Servlet too

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java
Signed-off-by: Lorenzo Addazi <lorenzo.addazi@mdh.se>
=> Fixes eclipse/xtext-core#1517

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/JavaFormatterGrammarTest.java
=> [#1625] Make test less strict to avoid failing because of bad serialize

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/extensions/InjectionExtension.java, org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/fileAware/validation/FileAwareTestLanguageValidator.java, org.eclipse.xtext.tests/build.gradle, org.eclipse.xtext.tests/src/org/eclipse/xtext/junit5/RunSuiteJUnit5.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/junit5/FileAwareTestLanguageValidationJunit5Test.java
[#1648] fixed regression in InjectionExtension
=> [#1648] fixed regression in InjectionExtension

org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguage.g, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguageLexer.java, org.eclipse.xtext.testlanguages.ide/src-gen/org/eclipse/xtext/testlanguages/noJdt/ide/contentassist/antlr/internal/InternalNoJdtTestLanguageParser.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguage.g, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguageLexer.java, org.eclipse.xtext.testlanguages/src-gen/org/eclipse/xtext/testlanguages/noJdt/parser/antlr/internal/InternalNoJdtTestLanguageParser.java, org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/noJdt/NoJdtTestLanguage.mwe2, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
[#1655] fixed k=x generation if k is set in parser options
=> [#1655] fixed k=x generation if k is set in parser options

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractJavaFormatter.java, org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextFormatterJava.java
=> [#1618] Delegate methods to simplify java formatter code.

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1925] update to MWE 2.12.1.M2
=> [eclipse/xtext#1925] update to MWE 2.12.1.M2

org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
=> updated versions in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#1934] update to ASM 9.1
=> [eclipse/xtext#1934] update to ASM 9.1

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final
=> [eclipse/xtext#1928] Bootstrap against MWE(2) 1.6.1/2.12.1 Final

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> [eclipse/xtext#1937] Update JUnit to 5.7.1

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.26.0

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#1944] update orbit to 2021-06
=> [eclipse/xtext#1944] update orbit to 2021-06

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
make guice version more explicit
=> make guice version more explicit

org.eclipse.xtext/src-gen/org/eclipse/xtext/common/services/TerminalsGrammarAccess.java, org.eclipse.xtext/src-gen/org/eclipse/xtext/services/XtextGrammarAccess.java
=> regenerated languages

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1947] adapt wizard for 2021-06
=> [eclipse/xtext#1947] adapt wizard for 2021-06

org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[#1684] fix services merging in maven lsp fat jars
=> [#1684] fix services merging in maven lsp fat jars

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
use tycho 2.3 with Java11/Target Platform 2021-06+
=> use tycho 2.3 with Java11/Target Platform 2021-06+

org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
=> mark MergeableManifest for removal

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> update to query 3.6.0

org.eclipse.xtext/src/org/eclipse/xtext/preferences/BooleanKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/EnumKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/IPreferenceValues.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/IPreferenceValuesProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/ITypedPreferenceValues.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/IntegerKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/MapBasedPreferenceValues.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceKeysProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceValuesByLanguage.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/StringKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/TypedPreferenceKey.java, org.eclipse.xtext/src/org/eclipse/xtext/preferences/TypedPreferenceValues.java
=> [#1703] Cleanup preferences API

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/lsMavenApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
bumped exec-maven-plugin to 3.0.0 in wizard
=> bumped exec-maven-plugin to 3.0.0 in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
use eclipse 2021-09 in target platform
DO NOT MERGE YET
=> use eclipse 2021-09 in target platform

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#1981] update to gson 2.8.7
=> [eclipse/xtext#1981] update to gson 2.8.7

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 2.4

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#1976] workaround for platform version range issue in gradle
=> [eclipse/xtext#1976] workaround for platform version range issue in gradle

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/ValidatorFragment2Tests.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
remove unnec. restriction for non xbase grammars
=> remove unnec. restriction for non xbase grammars

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/debug/TextRegionAccessToString.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractHiddenRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeRegion.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/StringRegion.java
comment.getGrammarElement() can be null thus toString should be able
to handle nulls
=> Fixed typo, NPE and small cleanup

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarConstraintProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/diagnostic/SequencerDiagnosticProvider.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/impl/Serializer.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/AssignmentFinder.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/ContextFinder.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/IContextFinder.java, org.eclipse.xtext/src/org/eclipse/xtext/service/DefaultRuntimeModule.java
use guice 5.0.1
different approach of serializer classes singletons to avoid oom races on parallel injection
=> use guice 5.0.1

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
=> use MWE2 2.12.2.M1

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#1978] update to asm 9.2
=> [eclipse/xtext#1978] update to asm 9.2

org.eclipse.xtext/src/org/eclipse/xtext/resource/containers/LiveShadowedAllContainerState.java
[#1734] improve performance of LiveShadowedAllContainerState.getContainedURIs
=> [#1734] improve performance of LiveShadowedAllContainerState.getContainedURIs

org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ManifestMergerTest.java
[#1744] ignore test on Java 16 and later
=> [#1744] ignore test on Java 16 and later

gradle/bootstrap-setup.gradle, gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
update to xtext-gradle-plugin 2.0.9
=> update to xtext-gradle-plugin 2.0.9

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
update xtext-gradle-plugin to 2.1.0
=> update xtext-gradle-plugin to 2.1.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/SocketServerLauncher.java
Fix port parsing in SocketServerLauncher
Fixes #1749
=> Fix port parsing in SocketServerLauncher

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/package-info.java
=> fix javadoc

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrToolFacade.java
[#1522] download via https first and try http on error only in AntlrToolFacade
=> [#1522] download via https first and try http on error only in AntlrToolFacade

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrToolFacade.java
=> deprecate setDownloadUrl

gradle/eclipse-project-layout.gradle
[#1774] fixed test language generation cleanup
=> [#1774] fixed test language generation cleanup

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
[eclipse/xtext#2004] update to gradle 7.3
=> [eclipse/xtext#2004] update to gradle 7.3

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2013] update to gson 2.8.8
=> [eclipse/xtext#2013] update to gson 2.8.8

org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
=> update shadow plugin

org.eclipse.xtext.testing/META-INF/MANIFEST.MF
[#1781] fix package import for org.junit.jupiter.api
=> [#1781] fix package import for org.junit.jupiter.api

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGeneratorFragment2.java
added ability to configure download url from workflow
=> added ability to configure download url from workflow

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
=> update to gradle 7.3.1

org.eclipse.xtext.util/src/org/eclipse/xtext/util/OnChangeEvictingCache.java
Add possibiliy to use custom capacity for cache adapters
=> Add possibiliy to use custom capacity for cache adapters

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/FoldingTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/folding/DefaultFoldingRangeProvider.java
[#1778] fix folding range line calculation
=> [#1778] fix folding range line calculation

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2020] consume classgraph from Xtext update site
=> [eclipse/xtext#2020] consume classgraph from Xtext update site

NOTICE.md, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2020] update to classgraph 4.8.138
=> [eclipse/xtext#2020] update to classgraph 4.8.138

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
=> update to gradle 7.3.2

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> bump jetty version in wizard

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
=> update to gradle 7.3.3

org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java, org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedNameInterning.java
Signed-off-by: Oliver Libutzki <oliver@libutzki.de>
=> Introduction of QualifiedNameInterning in order to configure QualifiedName.USE_INTERNING without using reflection

org.eclipse.xtext.ide/META-INF/MANIFEST.MF
=> fix downstream warnings

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release
=> eclipse/xtext#2025] update to mwe(2) 1.6.2/2.12.2 release

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#2021] update to tycho 2.6.0
=> [eclipse/xtext#2021] update to tycho 2.6.0

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> [#1794] bump jetty version

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> bump jetty version

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
=> switch to 2022-03

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2029] update to orbit 2022-03
=> [eclipse/xtext#2029] update to orbit 2022-03

org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/lsMavenApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/lsMavenApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> bump versions in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
bump to jetty 9.4.45. 
Fixes #1794
=> bump to jetty 9.4.45. 

gradle/versions.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/build.gradle, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
[eclipse/xtext#2034] bump xtext-gradle-plugin
=> [eclipse/xtext#2034] bump xtext-gradle-plugin

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2031] update to GSON 2.8.9
=> [eclipse/xtext#2031] update to GSON 2.8.9

org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.java
Fix NPE if there is no resource provider for an URI by checking for null
and defaulting to false if null, the null check is equivalent to the one
already present in getDeltasForDeletedResources. In addition mark the
URI for removal.
The resource provider can be null in our development environments or if
a persisted index is being reused after some language was de-installed.
=> Fix NPE if there is no resource provider for an URI

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/XtextVersionTests.java
=> support RC1 and RC2 too

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.27.0

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext2030] update to tycho 2.7.0
=> [eclipse/xtext2030] update to tycho 2.7.0

org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java
=> cleanup for #1848

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
=> update to gradle 7.4.1

org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/NestedClass1.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/NestedPackage1Factory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/NestedPackage1Package.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/impl/NestedClass1Impl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/impl/NestedPackage1FactoryImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/impl/NestedPackage1PackageImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/util/NestedPackage1AdapterFactory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/nestedPackage1/util/NestedPackage1Switch.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/NoLitClass.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/NoLitEnum.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/NoLiteralsFactory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/NoLiteralsPackage.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/impl/NoLitClassImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/impl/NoLiteralsFactoryImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/impl/NoLiteralsPackageImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/util/NoLiteralsAdapterFactory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/noLiterals/util/NoLiteralsSwitch.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/RootClass.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/RootEnum.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/RootFactory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/RootPackage.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/impl/RootClassImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/impl/RootFactoryImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/impl/RootPackageImpl.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/util/RootAdapterFactory.java, org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/generator/ecore/genmodelaccess/root/util/RootSwitch.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/ecore/GenModelAccessTest.genmodel
added missing copyright headers
=> added missing copyright headers

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/StringsTest.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java
=> added getLevenshteinDistance

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
bump maven-clean-plugin from 3.1.0 to 3.2.0
=> bump maven-clean-plugin from 3.1.0 to 3.2.0

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/wizard/WizardConfigurationTest.java, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.util/build.gradle, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext/META-INF/MANIFEST.MF, org.eclipse.xtext/build.gradle, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2028] switch to reload4j
=> [eclipse/xtext#2028] switch to reload4j

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
[eclipse/xtext#2051] update to gradle 7.4.2
=> [eclipse/xtext#2051] update to gradle 7.4.2

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1
=> [eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 2.7.1

releng/p2/pom.xml
=> bumped maven antrun plugin

NOTICE.md, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06
=> [eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
=> update to MWE 2.13.0.M2

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#2060] update to tycho 2.7.2
=> [eclipse/xtext#2060] update to tycho 2.7.2

org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.java
as we still need to iterate over the remaining set, we can be more
efficient by combining the two filters in the same iteration.
Signed-off-by: Rubén Porras Campo <Ruben.PorrasCampo@avaloq.com>
=> Avoid the creation of a HashSet just to filter elements

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#2064] update to tycho 2.7.3
=> [eclipse/xtext#2064] update to tycho 2.7.3

org.eclipse.xtext.ide.tests/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext.ide/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext.tests/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext.util/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext.xtext.generator/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext.xtext.wizard/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.xtext/.settings/org.eclipse.xtend.core.Xtend.prefs
=> cleanup xtend preferences

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/ServerTest.java, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/WorkspaceSymbolService.java, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend, org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/WorkspaceSymbolConfiguration.java, org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java
[#1793] update to lsp4j 0.13.0
=> [#1793] update to lsp4j 0.13.0

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[#1902] update to LSP4J 0.14.0
=> [#1902] update to LSP4J 0.14.0

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.28.0

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2068] use 2022-09 in wizard
=> [eclipse/xtext#2068] use 2022-09 in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 2.7.4

org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenApp/lsMavenApp.parent/lsMavenApp/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
=> bump maven-assembly-plugin

org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
=> more bumps

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java
Signed-off-by: Rubén Porras Campo <Ruben.PorrasCampo@avaloq.com>
=> Do not crash for non Xtext Resources

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/StorageAwareResource.java
That is, catch and log StackOverflowErrors when loading resources from
storage, and fall back to recreating the resource from source.
StackOverflowErrors can happen if the AST is deeply nested, since the
algorithm to load from storage uses recursion.
Signed-off-by: rubenporras <Ruben.PorrasCampo@avaloq.com>
=> Catch stack overflows when loading from storage

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2081] update to gson 2.9.0
=> [eclipse/xtext#2081] update to gson 2.9.0

org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/PdaUtil.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/NamedSerializationContextProvider.java, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SyntacticSequencerExtensions.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SyntacticSequencerExtensions.java, org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SyntacticSequencerPDAProvider.java
fix flaky generation of sequencers
=> fix flaky generation of sequencers

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/RenamePositionTest.java, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/IRenameService2.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/rename/RenameService2.java
[eclipse/xtext-core#1904] update to lsp4j 0.15.0
=> [eclipse/xtext-core#1904] update to lsp4j 0.15.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java
[#1944] fix crash with notebookservice default impl by providing a noop impl
=> [#1944] fix crash with notebookservice default impl by providing a noop impl

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
adapt to platform changes with junit 5
=> adapt to platform changes with junit 5

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
[eclipse/xtext#2087] switch from requireBundle to importPackage for junit5
=> [eclipse/xtext#2087] switch from requireBundle to importPackage for junit5

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractJavaFormatter.java
change baseclass for xbase formatter: make polymorphic dispatcher formatting in AbstractJavaFormatter callable from subclasses
=> change baseclass for xbase formatter: make polymorphic dispatcher formatting in AbstractJavaFormatter callable from subclasses

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.29.0

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#2096] update to tycho 2.7.5
=> [eclipse/xtext#2096] update to tycho 2.7.5

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.target/mavenTychoP2J11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2092] update to 2022-12 in wizard
=> [eclipse/xtext#2092] update to 2022-12 in wizard

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
bump jetty to 9.4.49.v20220914
=> bump jetty to 9.4.49.v20220914

NOTICE.md, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ11/mavenTychoJ11.parent/mavenTychoJ11.target/mavenTychoJ11.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J11/mavenTychoP2J11.parent/mavenTychoP2J11.target/mavenTychoP2J11.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson
=> [eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/AbstractDeclarativeIdeQuickfixProvider.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolutionAcceptor.java
Signed-off-by: pcr <Ruben.PorrasCampo@avaloq.com>
=> IllegalArgumentException thrown when applying quickfix

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsIntegrationTest.java, org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/UriExtensions.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.java
The given encoded URI string was wrongly decoded / re-encoded in some
cases.
=> [#1968] Improved handling of encoded URIs in UriExtensions 

org.eclipse.xtext/src/org/eclipse/xtext/build/ResolvedResourceDescription.java
=> Fixed logging in ResolvedResourceDescription

releng/releng-target/xtext-core.target.target
=> bump tycho bootstrapping

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[eclipse/xtext-core#1943] update to lsp4j 0.16.0
=> [eclipse/xtext-core#1943] update to lsp4j 0.16.0

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/folding/FoldingRangeService.java
For #1973 
Signed-off-by: pcr <Ruben.PorrasCampo@avaloq.com>
=> Fix NPE if document of resource is null

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[eclipse/xtext-core#1986]update to lsp4j 0.17.0
=> [eclipse/xtext-core#1986]update to lsp4j 0.17.0

NOTICE.md, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#2104] update to asm 9.4
=> [eclipse/xtext#2104] update to asm 9.4

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml, org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2106] Update to MWE 2.14.0.M1
=> [eclipse/xtext#2106] Update to MWE 2.14.0.M1

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalAcceptor.java, org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/contentassist/ContentAssistService.java
Signed-off-by: rubenporras <Ruben.PorrasCampo@avaloq.com>
=> Rename private variable to follow public method name

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[eclipse/xtext-core#1993] update to lsp4j 0.18.0
=> [eclipse/xtext-core#1993] update to lsp4j 0.18.0

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2112] Fix Orbit signing problem
=> [eclipse/xtext#2112] Fix Orbit signing problem

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/quickfix/DiagnosticResolution.java, org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java, org.eclipse.xtext/src/org/eclipse/xtext/build/ClusteringStorageAwareResourceLoader.java
make full use of Java 11 Deprecated annotation
=> make full use of Java 11 Deprecated annotation

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2112] switch back to orbit 2022-12 in wizard
=> [eclipse/xtext#2112] switch back to orbit 2022-12 in wizard

releng/releng-target/xtext-core.target.target
[eclipse/xtext#2112] switch back to orbit 2022-12
=> [eclipse/xtext#2112] switch back to orbit 2022-12

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF
[eclipse/xtext-core#2004] Update to lsp4j 0.19.0
=> [eclipse/xtext-core#2004] Update to lsp4j 0.19.0

org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java
replace File.createTempFile with Files.createTempFile.toFile
=> replace File.createTempFile with Files.createTempFile.toFile

org.eclipse.xtext.tests/src/org/eclipse/xtext/util/LineFilterOutputStreamTest.java
=> also mark test as deprecated

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.30.0

releng/releng-target/xtext-core.target.target
bootstrap against 2.29 release
=> bootstrap against 2.29 release

org.eclipse.xtext.util/src/org/eclipse/xtext/util/GraphvizDotBuilder.java
[#2010] fix Java 18 Runtime.exec deprecation
=> [#2010] fix Java 18 Runtime.exec deprecation

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/smoketest/internal/RunnerBuilder.java
[eclipse/xtext#2011] fix junit depr
=> [eclipse/xtext#2011] fix junit depr

org.eclipse.xtext.tests/testdata/wizard-expectations/eclipsePlugin/eclipsePlugin.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/eclipsePluginP2/eclipsePluginP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.ui.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.xtend, org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/JUnitFragment.java, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.java
[#2029] remove old test plugins from wizard, add new ones
=> [#2029] remove old test plugins from wizard, add new ones

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
=> update to jetty 9.4.50

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
[eclipse/xtext#2102] switch to Tycho 3.0.1 for Java 17
=> [eclipse/xtext#2102] switch to Tycho 3.0.1 for Java 17

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.28.1

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/GlobalRegistries.java
remove more outdated code switches for old targets
=> remove more outdated code switches for old targets

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java, releng/releng-target/xtext-core.target.target
[eclipse/xtext#2118] update to orbit 2023-03
=> [eclipse/xtext#2118] update to orbit 2023-03

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java, org.eclipse.xtext/META-INF/MANIFEST.MF
[eclipse/xtext#2126] bump reload4j
=> [eclipse/xtext#2126] bump reload4j

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/formatter/FormatterTestHelper.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormatterTestLanguageJavaFormatter.java, org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/JavaFormatterTest.java
[#2058] fix assertAllWhitespaceIsFormatted
=> [#2058] fix assertAllWhitespaceIsFormatted

org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/debug/TextRegionsWithTitleToStringTest.java, org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/LineRegion.java
[#2055] fix newline at end of file
=> [#2055] fix newline at end of file

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 3.0.2

org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenFatjar/lsMavenFatjar.parent/lsMavenFatjar.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.ide/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.ide/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
bumped some maven plugins in wizard
=> bumped some maven plugins in wizard

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2131] update to gson 2.10
=> [eclipse/xtext#2131] update to gson 2.10

org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
[eclipse/xtext#2131] update to GSON 2.10.1
=> [eclipse/xtext#2131] update to GSON 2.10.1 

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
=> update to tycho 3.0.3

gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties, org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties
[eclipse/xtext#2138] update to gradle 7.6.1
=> [eclipse/xtext#2138] update to gradle 7.6.1

org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/lsGradleFatjar.ide/build.gradle, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.java
[eclipse/xtext#2136] fix deprecation with gradle 8
=> [eclipse/xtext#2136] fix deprecation with gradle 8

gradle/versions.gradle, org.eclipse.xtext.ide.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testing/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF, org.eclipse.xtext.tests/META-INF/MANIFEST.MF, org.eclipse.xtext.util/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.ide/META-INF/MANIFEST.MF, org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF, org.eclipse.xtext/META-INF/MANIFEST.MF, releng/p2/category.xml, releng/p2/pom.xml, releng/pom.xml, releng/releng-target/pom.xml
=> [releng] Update Xtext version to 2.31.0

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle.web/build.gradle, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.web/pom.xml, org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml, org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend, org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
[#2081] update to jetty 9.4.51.v20230217
=> [#2081] update to jetty 9.4.51.v20230217
